### ISSUE TITLE
Allow pywemo to subscribe to multiple services

### ISSUE THREAD

**Issue by pavoni** [pywemo/pywemo#115]
At present the pywemo subscription code only subscribes to the `basicevent` services.

This updates on the most important events like (on / off) - but doesn't work for everything (eg for wemo insight switches - it doesn't update when the power consumption is changed (unless it also triggers a change in or out of standby - which does trigger a `basicevent`).

For this reason I had to leave polling turned on in Home Assistant for switches (@sqldiablo - you might want to check this still works in your recent HA refactor) so that insight parameters would still be updated correctly.

Insight parameter changes are reported by a subscription to `insight`. I expect a number of other wemo devices that report their state via other services such as  https://github.com/pavoni/pywemo/issues/6).

The ghost of my attempt to update this is here
https://github.com/pavoni/pywemo/blob/master/pywemo/subscribe.py#L119

The current re-subscribe code is set up to handle a single subscription per device code so will need to be refactored to support this.

cc @sqldiablo in case you are interested in taking a look at this.

**Comment by sqldiablo** [comment]
Yeah, I definitely intend to tackle the subscriptions. It's probably second on my list after rediscovery. I've deliberately kept HA don't polling as well as subscription updates because I was setting some inconsistency, especially after a rediscovery. I'd like to get subscriptions working well enough to turn polling off in HA.

**Comment by pavoni** [comment]
Perfect - I skimmed your HA updates - but missed you'd kept the polling.

I had a failed attempt to enhance the subscription mechanism a while back which required an HA patch to remove! It ended up spamming wemos with multiple subscriptions until they crashed!

**Comment by sqldiablo** [comment]
It's sneaky. Polling is the default, so I removed the property from the object in HA, which makes it default to do polling.

**Comment by minscof** [comment]
I am interesting by this feature : is there someone working on this ?

**Comment by pavoni** [comment]
@minscof I don't believe so.

It's quite tricky as it requires an overhaul of the subscription mechanism so that it will support multiple subscriptions (all with their own renewal schedule) in each pywemo object.

Also for most users it isn't too big a deal, the other attributes are available on a background poll - and the on/off (including threshold crossing for the insight switch) are updated in real time via the basicevent service.

What do you need this for?
