### ISSUE TITLE
pywemo in action!

### ISSUE THREAD

**Issue by eliotlandrum** [pywemo/pywemo#133]
This isn't a problem, just wanted to share with you what I'd been working on using pywemo for. 

https://devpost.com/software/tokenized-autonomous-vehicle-charging-with-blocklet-1ws73v

There's a video at the top. It doesn't show it, but the Roomba has a Pi inside the vacuum area and there's a Pi for the dock as well (not shown). The Roomba charging dock is actually plugged into a WeMo Insight switch and the dock's Pi enables the power after a contract has been established with the bot. While the bot is charging, kWh are shared to the contract and it is paid for the energy used. When the robot leaves the dock, the charging cycle is complete,  and the contract if finalized, the power is disabled again via the switch. Thanks for the nice work on this library and I appreciate you sharing it with the world. :)

**Comment by pavoni** [comment]
Thanks for sharing - very nice demo. Really great to hear the the code is useful for something interesting like that.

I also use the power monitoring of an insight. My espresso coffee machine take 5 mins to warm up - so I monitor the power usage, and run an event when the coffee machine thermostat triggers and the power consumption drops.

So basically a light in my living room turns red when the coffee machine turns on, and then turns green when it's up to temperature.

Thanks for taking the time to pass this on - and good luck with the real project!

**Comment by sqldiablo** [comment]
@eliotlandrum, that's a super cool demo. Thanks for sharing this. :-)
