### ISSUE TITLE
Malformed device XML causes exception during discovery

### ISSUE THREAD

**Issue by sqldiablo** [pywemo/pywemo#135]
This is a repost of https://github.com/home-assistant/home-assistant/issues/23744, as the issue is in pyWeMo and not Home Assistant.

When a device (sometimes a WeMo, and sometimes another device on the network that responds during discovery) returns malformed XML or XML other than the expected response, it causes the pyWeMo library to throw an exception. More details are provided in the linked issue.

**Comment by chelming** [comment]
I've been able to reproduce this by renaming a plug. When the plug gets renamed it returns malformed (incomplete) XML until a full power cycle.

**Comment by pavoni** [comment]
Given the investigation above - I think this is (or hopefully was) a wemo firmware bug. Probably not something we should catch here.

Happy to re-consider catching XML error if this (or something similar) comes back.
