### ISSUE TITLE
Python noob needs help..How to get instant power?

### ISSUE THREAD

**Issue by simmyr94** [pywemo/pywemo#144]
Dear developers, 

I'm new to python and I'm trying to use the module to get the instant power of my insight switch

here is the code

```
import pywemo
devices = pywemo.discover_devices()

print(devices)
print(devices[0].get_state())
print(devices[0].insight_params())
```

error:  'dict' object is not callable

I'm pretty sure I did wrong, but can someone explain to me the right way please?

Thanks a lot.

**Comment by sqldiablo** [comment]
What output do you get when you just run this?

```python
import pywemo
devices = pywemo.discover_devices()

print(devices)
```

**Comment by simmyr94** [comment]
Dear Mr. Belebczuk
Thank you for your timely reply. 

for 
```
import pywemo
devices = pywemo.discover_devices()

print(devices)
```
the output is 

```
[<WeMo Insight "Test1">]

Process finished with exit code 0
```

**Comment by pavoni** [comment]
Sorry for the slow reply `insight_params` is an instance variable, rather than a method. So you can so you can see the info available like this:-
```
>>> print(devices[2].insight_params)
{'state': '8', 'lastchange': datetime.datetime(2019, 12, 20, 16, 37, 13), 'onfor': 4877, 'ontoday': 0, 'ontotal': 48928, 'todaymw': 0, 'totalmw': 33883013, 'currentpower': 0, 'powerthreshold': 8000}
```
You can get individual details:-
```
>>> print(devices[2].today_kwh)
0.0
```

The `insight_params` are cached - so to force a refresh use 
```
>>> devices[2].get_state(True)
8
```

**Comment by simmyr94** [comment]
That works! 


Thank you guys so much. Cannot get this done without Mr. Belebczuk and Mr. Dowling's kindly help.

Here is the code to display real time power usage for future reference. 

```
import pywemo
devices = pywemo.discover_devices()

def refresh(): #The insight_params are cached - so to force a refresh use
    devices[0].get_state(True)
    global params
    params = devices[0].insight_params

def currentPower():
    print(params.get('currentpower')/1000)

while True:
    refresh()
    currentPower()
```
