### ISSUE TITLE
Improvement wemo insight

### ISSUE THREAD

**Issue by minscof** [pywemo/pywemo#154]
The _x parameter is the wifi signal power, can you add it to the code ?
Thx

> def parse_insight_params(self, params):
>         """Parse the Insight parameters."""
>         (
>             state,  # 0 if off, 1 if on, 8 if on but load is off
>             lastchange,
>             onfor,  # seconds
>             ontoday,  # seconds
>             ontotal,  # seconds
>             timeperiod,  # pylint: disable=unused-variable
>             _x,  # This one is always 19 for me; what is it?
>             currentmw,
>             todaymw,
>             totalmw,
>             powerthreshold

**Comment by sqldiablo** [comment]
You've gone that far, why not submit a pull request for that change? 🙂

**Comment by sqldiablo** [comment]
This feature has been published to Pypi as pywemo version 0.4.44
