### ISSUE TITLE
WeMo setup without account

### ISSUE THREAD

**Issue by ViViDboarder** [pywemo/pywemo#161]
This is an enhancement request. I'm hoping that at least for now it may be possible to install an older version of the Android app and figure out _how_ setup is done locally and mimic that.

**Comment by pavoni** [comment]
What's the concern - did they change the app to require cloud access?

**Comment by ViViDboarder** [comment]
Yes, the app has been updated such that you cannot connect a WeMo to your wifi unless you create and link it to your cloud account.

**Comment by pavoni** [comment]
Got it. 

Suspect it's quite a bit of work - so will need someone with some time and determination!

**Comment by ViViDboarder** [comment]
Yea. Non-trivial I imagine. I was originally thinking to just use an MITM proxy to see the communication, but then remembered the setup happens when connected to the WeMo adhoc network. So this may be tricky.

**Comment by Spectre5** [comment]
PR #179 should provide this functionality.

**Comment by pavoni** [comment]
Now supported in `0.5.4` many thanks to @Spectre5
