### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by RGSMA** [pywemo/pywemo#162]
Noob question: On a Wemo Insight, what is the currentpower parameter? Thanks

**Comment by pavoni** [comment]
It’s the current power consumption of the attached device, in milli-watts.

**Comment by RGSMA** [comment]
Thanks. I thought so but wasn't aware that my towel warmer was drawing 150 watts.

**Comment by pavoni** [comment]
Those sort of power measurements can be very interesting!
