### ISSUE TITLE
Please file/pin Releases....

### ISSUE THREAD

**Issue by onkelbeh** [pywemo/pywemo#163]
Hi Greg,

I am using your component for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository), hope you don't mind.

Therefore I need source files in Pypi's SDIST format, or Github archives.
The source files on Pypi contain some code with outrageous paths, and no setup.py,
and: you do not file releases on Github.

At least, your release list on Github should look like this:
<img width="454" alt="Bildschirmfoto 2020-09-01 um 21 01 34" src="https://user-images.githubusercontent.com/42828703/91895069-e9cd0b00-ec96-11ea-9d90-6d018e8084c8.png">

To fix this, I created a fork of your code, and added the missing tags.
Until you fix this, I will point the SRC_URI of the Gentoo Ebuilds to the [fork](https://github.com/onkelbeh/pywemo) to have consistant snaps of the releases.

I did this with:
```bash
  699  git tag 0.4.46 d9cd5c2
  701  git tag 0.4.45 8727d71
  702  git tag 0.4.44 24ddfc8
  706  git tag 0.4.42 e165292
  707  git tag 0.4.43 2c13cc0
  708  git tag 0.4.34 10280d0
```
Your commit id's may differ.
Then I pushed the tags to github:

```bash
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git tag
0.4.34
0.4.42
0.4.43
0.4.44
0.4.45
0.4.46
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.34
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.34 -> 0.4.34
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.42
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.42 -> 0.4.42
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.43
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.43 -> 0.4.43
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.44
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.44 -> 0.4.44
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.45
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.45 -> 0.4.45
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo/tmp/pywemo # git push origin 0.4.46
Gesamt 0 (Delta 0), Wiederverwendet 0 (Delta 0), Pack wiederverwendet 0
To https://github.com/onkelbeh/pywemo.git
 * [new tag]         0.4.46 -> 0.4.46

```
So I get consistant archives:
```bash
root@g18-hasstest:/usr/portage/homeassistant/dev-python/pywemo # ls -la /usr/portage/distfiles/pywemo-0.4.*
-rw-rw-r-- 1 portage portage 38251  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.34.tar.gz
-rw-rw-r-- 1 portage portage 42439  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.43.tar.gz
-rw-rw-r-- 1 portage portage 43927  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.45.tar.gz
-rw-rw-r-- 1 portage portage 43923  1. Sep 21:22 /usr/portage/distfiles/pywemo-0.4.46.tar.gz
```

The fix for issue [60](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/60): https://github.com/onkelbeh/HomeAssistantRepository/commit/abe802941ea38bd3ff793a69f45e214cd30ed7db
Please do this for at least the versions pinned in Home Assistant.

Thank you very much.

**Comment by onkelbeh** [comment]
Aehm, just saw `pyvera` is also from here, why don't you just do it like you do it in `pyvera`?

**Comment by pavoni** [comment]
It was kindly set up and contributed by someone who knows more about releasing than I do!

**Comment by pavoni** [comment]
Can I ask why you forked this instead of proposing a PR?

**Comment by onkelbeh** [comment]
Hi Greg,

sure you can :-)

As far as I know a pull request cannot contain tags or releases.

Home Assistant relies on specific (very pinned) versions of it's components, so it is not enough to have the current source. I just used the fork to generate the missing source archives for your older releases. I did not change your code.

For normal, I keep 3-6 releases of the ebuilds (depending on HA's release cycles). You could start setting tags with your next release, and we just let the oldies die. But it is not very difficult to [add the previous tags](https://devconnected.com/how-to-create-git-tags/), see my [first comment](https://github.com/pavoni/pywemo/issues/163#issue-690399323), but I am not sure if the refs are the same at your local repository, could be these have to be adjusted.

As soon as I can get the archives from here I will remove the clone and let my SRC_URI's point to the archives here.

Or, much better: I would prefer source archives from Pypi, because these could use Gentoo's mirror system. You already have these, but they are packed with a very long absolute path. And they are incomplete.
Compare, for example, [your current Pypi SDIST](https://files.pythonhosted.org/packages/e9/07/5ab6651a88c7df6b1903fac3a1a3efd69c3524aadd160b664a5bbf6c3043/pywemo-0.4.46.macosx-10.15-x86_64.tar.gz) with [my version](https://github.com/onkelbeh/pywemo/archive/0.4.46.tar.gz
).

I just looked at your [workflows](https://github.com/pavoni/pyvera/tree/master/.github/workflows) and [scripts](https://github.com/pavoni/pyvera/tree/master/scripts) at `pyvera`. Perfect, if you'd use these, they will do it correctly.

Currently I have forked ~5 other components with similar problems. Not a big thing, but generating useless additional work.

**Comment by onkelbeh** [comment]
FYI: Just went through and cleaned up: currently I have forked 11 components to get valid source archives.
During cleanup I could remove 9 others :-)

**Comment by pavoni** [comment]
Well in the sprit of open source I'd welcome a contribution!

Otherwise will investigate when I have time to learn more about the release process (applies to my other repos too).

Don't know if you saw - but the PR you did propose here fails lint. Will obviously need to pass before I look at it in more detail.

**Comment by pavoni** [comment]
@onkelbeh I think the release process and tagging is now sorted.

Happy to tag the old versions if you're willing to dig out the relevant commit ids.

**Comment by onkelbeh** [comment]
Sure, did it already in the post above :-)

Here are the full commit id's:
```bash
root@g18-hasstest2:/tmp/pywemo # git log | grep 80d0
commit 10280d054bc8e0b0f7b3f24498c29ea45ae368f5
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.34 10280d054bc8e0b0f7b3f24498c29ea45ae368f5
root@g18-hasstest2:/tmp/pywemo # git log | grep 5292
commit e1652926c8bab668ae8a5f03ff671049970f78b4
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.42 e1652926c8bab668ae8a5f03ff671049970f78b4
root@g18-hasstest2:/tmp/pywemo # git log | grep 3cc0
commit 2c13cc0171b1fdc2671738a7080a0bdd8b9c022f
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.43 2c13cc0171b1fdc2671738a7080a0bdd8b9c022f
root@g18-hasstest2:/tmp/pywemo # git log | grep dfc8
Merge: 24ddfc8 d6323b8
commit 24ddfc8391d000e01304c586f102f0e3a07cf254
commit e9c1ccd291d4b27f0fa2616a348fdfc8a74d9416
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.44 24ddfc8391d000e01304c586f102f0e3a07cf254
root@g18-hasstest2:/tmp/pywemo # git log | grep 7d71
Merge: 8727d71 9cdf3c8
commit 8727d71e7a75704bbdb4044618590a22d232186d
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.45 8727d71e7a75704bbdb4044618590a22d232186d
root@g18-hasstest2:/tmp/pywemo # git log | grep d5c2
Merge: d9cd5c2 d4271e9
commit d9cd5c246624ec7b81d63fcb6a02c983750f60f8
root@g18-hasstest2:/tmp/pywemo # git tag 0.4.46 d9cd5c246624ec7b81d63fcb6a02c983750f60f8
root@g18-hasstest2:/tmp/pywemo # git tag
0.4.34
0.4.42
0.4.43
0.4.44
0.4.45
0.4.46
0.5.0
root@g18-hasstest2:/tmp/pywemo #
```
better viewable in color:
<img width="647" alt="Bildschirmfoto 2020-09-12 um 16 40 06" src="https://user-images.githubusercontent.com/42828703/92997865-bb60f280-f516-11ea-9546-afc551da1f94.png">

I have no write access, github refuses to accept the requests without:
```bash
root@g18-hasstest2:/tmp/pywemo # git push origin 0.4.34
ERROR: Permission to pavoni/pywemo.git denied to onkelbeh.
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
   [128]   root@g18-hasstest2:/tmp/pywemo #
```

PS: good job :-)

**Comment by onkelbeh** [comment]
Will review my Ebuilds soon: https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/178

**Comment by sqldiablo** [comment]
@onkelbeh I've tagged releases back to 0.4.34.

**Comment by pavoni** [comment]
@sqldiablo Thanks for doing that!

**Comment by onkelbeh** [comment]
Thats cool, thanks a lot.
 - fork removed, updat eold SRC_URI's
 - bump pywemo-0.5.0, SRC now is Pypi
https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/6e95c5c362e389eb32f330445ec654642da43e4f
