### ISSUE TITLE
Listening for Motion?

### ISSUE THREAD

**Issue by GSVNoFixedabode** [pywemo/pywemo#168]
Request for help here:
Is there a HowTo for setting up listening for a Motion trigger? I can see my Motion device and read the current state although that takes a number of seconds to return a value.  I don't want to be actively polling it every half second, then waiting n seconds for each result.  Is there a way to set this up to listen to Motion or subscribe to Motion so a job can be triggered when Motion changes state?  Thanks.
(Pi 1B, Aug20 Raspbian)

**Comment by pavoni** [comment]
Take a look at https://github.com/pavoni/pyvera/blob/master/examples/device_listener.py for an example

I'm afraid the documentation around this isn't great- but this is called a subscription in the code.

**Comment by pavoni** [comment]
I'm going to close this for now - but re-open if you need more help.
