### ISSUE TITLE
Port detection fails when using DNS hostname

### ISSUE THREAD

**Issue by joshuaboniface** [pywemo/pywemo#169]
Attempting to connect to a device via hostname with PyWemo appears to fail:

```
$ host basement-mini01
basement-mini01 has address 10.0.0.62
$ pip list | grep pywemo
pywemo (0.4.46)
$ python3
>>> import pywemo
>>> address = "basement-mini01"
>>> port = pywemo.ouimeaux_device.probe_wemo(address)
>>> print(port)
None
>>> address = "10.0.0.62"
>>> port = pywemo.ouimeaux_device.probe_wemo(address)
>>> print(port)
49153
```

Ideally, this should work equally well with a hostname or IP address.

Came to this conclusion after determining that my previous HomeAssistant configuration, using the Wemo module there, which in turn uses PyWemo, stopped working after a recent update. I am using DNS hostnames in the configuration rather than direct IPs, and verified as above. So this did work at some point in the past (I was on a very old install), but no longer does.

**Comment by joshuaboniface** [comment]
Doing some more digging, this actually looks to be a Wemo-side problem. Hitting the device with a hostname returns a 500, while hitting it with an IP returns a 200 as expected. Perhaps PyWemo should attempt to resolve the IP itself, then probe using the actual IP?

**Comment by joshuaboniface** [comment]
>Please note that you need to use ip addresses as shown above, rather than hostnames, otherwise the subscription update logic won't work.

This is very unfortunate, perhaps it should be updated to mention that devices will sometimes fail with hostnames for their own reasons as well.

**Comment by pavoni** [comment]
Interesting catch. Not sure it's a big deal since most people use discovery anyway (although this is unreliable for me).

We should update the docs as you suggest.

PR welcome - both for the documentation - and the code if you feel strongly - although with what you've discovered sounds like there may be other hidden issues!

**Comment by joshuaboniface** [comment]
Indeed, I'll do a PR to update the docs just to make note of it.

I don't use discovery myself since my PyWemo user (HomeAssistant) is on a different network from my WeMo devices, so I specify everything directly by hostname (and I use those because I have 12+ devices to remember!) - I definitely agree this is an unusual configuration for most home users.

FWIW I've submitted a fix upstream to HASS: https://github.com/home-assistant/core/pull/42101 This simply translates hostname->IP at the highest layer where I personally enter the hostname, but a fix here might be a better solution - I just didn't see a good place to do it simply! I tried at first just modifying the function I was calling above (`pywemo.ouimeaux_device.probe_wemo`), but that didn't persist. I made a similar modification below in the `Device` class initializer, but this doesn't help with the higher-level functions if used directly, and doesn't address that other underlying issue with hostnames. ~I'll take a gander further after studying the code a bit more!~ I think just documenting this is probably OK, and leave it up to your module's users to handle this, unless you can see a clean way to handle it.

**Comment by pavoni** [comment]
As you probably guessed the 'non discovery' code started in HA, and then was just added to the documentation here. 

I think HA is the main user of the library anyway - so what you've done with the PR there is probably the best way forward, along with the doc changes you've made.

Will leave you to close if you're comfortable with this as an answer.

**Comment by pavoni** [comment]
I saw the comment on the HA PR.

Would be happy if you wanted to add some sort of utility function to handle the non discovery set up more slickly, and then it could be used directly and in HA.

The non discovery set up could do with improvement anyway - the process here is a bit over complex!

https://github.com/pavoni/pywemo

**Comment by joshuaboniface** [comment]
Alright, given the answer there that my workaround isn't allowed, perhaps fixing it in here is saner. It'll probably take me a little longer to come up with a good solution but so far not outside my abilities, so I'll keep hacking away at it. If HA is the main (only) consumer that helps narrow it down - once I understand how HA uses it I can base it around that!

**Comment by pavoni** [comment]
HA has the function below - which should really be in pywemo.

So you could create a version in pywemo - add your host lookup code - and then change HA to use it

```
def setup_url_for_address(host, port):
    """Determine setup.xml url for given host and port pair."""
    if not port:
        port = pywemo.ouimeaux_device.probe_wemo(host)

    if not port:
        return None

    return f"http://{host}:{port}/setup.xml"

```

Not quite sure where it belongs - but probably in `discovery`

No changes needed to the other code here except the documentation because the `non discovery` process has always been manual.

And should be an easy change in HA because you can just remove their function and call the pywemo version.
