### ISSUE TITLE
Handle events and subscriptions

### ISSUE THREAD

**Issue by pavoni** [pywemo/pywemo#17]
Looks like it might be possible to make WeMo event driven using upnp subscriptions and events.

http://www.hardill.me.uk/wordpress/2015/01/14/wemo-event-notifications/

javascript sample here
https://gist.github.com/hardillb/2fce5fe7643a6f91dc75

I'll try and take a look at this when I have some time.

**Comment by philipbl** [comment]
There seems to be support for this already built in (see [subscribe.py](https://github.com/balloob/pywemo/blob/master/pywemo/subscribe.py)). There is also an example of it in ouimeaux called [watch.py](https://github.com/iancmcc/ouimeaux/blob/feature/examples/ouimeaux/examples/watch.py).
