### ISSUE TITLE
Device Factory Reset/Restore

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#171]
This is more of a question than an issue, but I'm not really sure where else to post it.  I'm curious if it is possible to do a full factory reset using pywemo?  I've looked at my switches and I've played around with some of the functions I found using the "explain" method as well as poked around in the _config base object, but I didn't find anything related to a full reset.  I'm looking for the equivalent of "Factory Restore" in the app which claims to "Erase all settings and returns it to default", per the screen shot on the Belkin support website.  Since this can be done via the phone app, I'm assuming that it can be done via uPnP using pywemo.  Any insights or pointers on how to achieve this?

**Comment by pavoni** [comment]
Hi @Spectre5 - no idea myself - but will leave this here in case anyone else has any suggestions.

Will likely require someone doing some digging much as you have done to try and discover if there is an api call somewhere!

**Comment by Spectre5** [comment]
I hope someone else has some ideas!  I see that there are 4 open ports (49153/tcp - 49156/tcp), I wonder if maybe there is some undocumented command that Belkin passes to a specific port.  Perhaps someone more adept than me at intercepting the communication between the app and the device could figure it out by doing a reset from the app and see what gets passed.

**Comment by Spectre5** [comment]
I brushed up on my wireshark skills and got this figured out.  It is in fact the ReSetup method as I'd originally thought.  Funny enough, I tired passing both Reset=0 and Reset=1 to the function but wireshark showed that the correct code for a full factory restore is actually Reset=2.  I was close!  So assuming that "device" is your wemo object, then this works for me to do a full factory restore (erase all settings and wifi connection information):

    >>> device.firmwareupdate.GetFirmwareVersion()
    {'FirmwareVersion': 'FirmwareVersion:WeMo_WW_2.00.11452.PVT-OWRT-SNSV2|SkuNo:Plugin Device'}
    >>> device.basicevent.ReSetup(Reset=2)
    {'Reset': 'success'}

So far I've only tested this with a WeMo Mini socket plug (US).

![wemo-factory-restore](https://user-images.githubusercontent.com/31610422/97775784-96edc380-1b20-11eb-8e29-5d989acbadba.png)

**Comment by pavoni** [comment]
Great detective work.

There seem to be three gui reset options - so guess they may be 0, 1 & 2.

PR welcome when you’re ready.

Also happy to test this on one of my old plugs.

BTW why do you want to reset the devices? Would have thought this would be a rare need.

**Comment by Spectre5** [comment]
You're probably right that 0 and 1 might be the other reset options, although I don't recall either of them resetting the wireless settings, which one of the other methods should do.  I did notice that one of them, I forget which, reset the "friendly name" of the device, so it did do something.  Maybe I'll reset the device a few more times to figure out which each code is with certainty.

I'll look into resetting the other two devices I have, an in wall switch and an in wall dimmer.  If I create a PR, would you want a reset option in the Device class (assumes it is the same for all devices, which I can't confirm) or in the Switch class?

As for you last point, I use home assistant for controlling my wemo devices (which uses pywemo as you're surely aware).  This works great and is much more reliable that using the Belkin app, so essentially my desire is to get rid of the Belkin app all together and have my own script to reset the devices (if and as needed) as well as to set them up.  This way, if I get any new wemo devices, I wouldn't need to re-install the Belkin app at all.  The reset isn't super critical as I could reset them physically, but it is nice to have it all in one interface.

**Comment by Spectre5** [comment]
So in my app there are 3 different "reset" options:

- Clear Personalized Info - Erase product name, icon and rules.
- Change Wi-Fi - Connect your Wemo to a new Wi-Fi with all of your personalized info.
- Factory Restore - Erases all settings and returns it to default.

I think the factory restore would essentially just be a combination of the first two.  Anyway, here is what I found out for these:

- Factory Restore --> Reset=2
- Change Wi-Fi --> Reset=5
- Clear Personalized Info --> I have not been able to determine using wireshark.  It appears that this option does not send the SOAP command locally via HTTP like the other two, but instead communicates to an AWS server which then delivers the SOAP command through TLS and thus I'm unable to see the details.  Actually, I think many of the commands in the app now do this, even when on the same network, as I also don't see the traffic for toggling the lights either, just the various "Get" commands are local as far as I can tell.  I may play around with it some more out of curiosity...

**Comment by Spectre5** [comment]
Ok, for some reason this bugged me more than it should, so I investigated this a bit more.  I created a VM (virtual machine) using Android-x86 and loaded an old wemo app on it (version 1.24) from apkmirror.  This older app version was from before Belkin decided to force registered user accounts and pushing (almost) everything through SSL/TLS and the cloud - which is the main reason I want to move away from the Belkin app!  So, in other words, this older app version is where commands were still sent through unencrypted channels and locally.  In this case, the two later options are the same the final one, "Clear Personalized Info" is now discovered (Reset=1)!  The naming of the reset options are slightly different in this app, but they are effectively all the same thing (confirmed with wireshark).  So, here is the full list:

- Clear Personalized Info --> Reset=1
  - This option also separately sent ChangeFriendlyName(FriendlyName="Wemo Mini"), so that may be required to "reset" the name of the device.
- Change Wifi --> Reset=5
- Factor Restore --> Reset=2

I have no idea what other numbers for ReSetup would do (maybe nothing!).  To summarize once more, in another way:

- ReSetup(Reset=1) --> should clear any icon and any set rules (and maybe friendly name, otherwise you may need to use ChangeFriendlyName to "reset" it)
- ReSetut(Reset=5) --> should clear your wifi settings, but save the icon, rules, and friendly name
- ReSetup(Reset=2) --> should clear everything, as if the device is new out-of-the-box

**ALL** of this is only tested with my wemo mini plug-in socket plug (US version).

**Comment by Spectre5** [comment]
Note also that a future wemo firmware could change the function names, codes, etc such that local control solutions like pywemo would no longer work, thus forcing users to use the app, which now requires internet access even just to turn on a switch.  If they do this, then there would be no easy way to update pywemo or another library to still work since the encryption would make it difficult/impossible to know what the app sent the device.  So if you want to be certain you can maintain local control on your current devices, you may want to consider not updating the firmware anymore (and/or putting the wemo devices on a separate vlan without internet access).

**Comment by pavoni** [comment]
Thanks for the info - and good tip about being careful about updating firmware.

Given all your detective work - will you put a PR together?

Feel free to add a firmware warning to the README if you feel included!

(And more than happy to test on one of my UK insight plugs when it's helpful)

**Comment by Spectre5** [comment]
Yup, I'll start a PR for discussion and add a working example soon.

**Comment by Spectre5** [comment]
Just a quick update on this - I'm getting close to finishing this and my current version works great for my devices.  I will make a PR in another day or two, after I get a little more time to clean it up.

**Comment by esev** [comment]
@Spectre5 I'm interested in disconnecting my devices from the cloud. Is that possible now? It wasn't clear to me from the documentation which type of reset would make this happen. If it is possible, which type of reset will do this?

I'm mainly looking to avoid the red flashing light that happens when the Dimmer/LightSwitch device is cut-off from the internet.

**Comment by Spectre5** [comment]
Yes, it should be possible!  You can also just use the app itself to reset them (I'd do a full factory reset myself), and then connect to their local wifi and use the setup method from pywemo to set them back up (connect to your local wifi only).

For doing multiple devices semi-automatically, I've used my script here a number of times with good success:
https://github.com/Spectre5/pywemo-setup

Also, please update the documentation afterward to make it more clear, if it isn't!  Especially after you've used it.

**Comment by Spectre5** [comment]
But, I believe/hope that using the "factory_reset" method on the device in pywemo would also do the same thing as the factory reset in the app. It is possible that the newer app versions do something else, perhaps to "unregister" it from you account?  But in the older version I used for this (pre-forced account creation), I didn't see anything to that effect.  But that is why I might just use the app to fully reset them if you have it anyway, just in case it does something more.

**Comment by Spectre5** [comment]
And this is how my devices are setup now, I don't have the app on my phone anymore and I've done a number of reset-setup cycles while doing various testing.  You could even put them on a separate vlan without internet access, if you wanted to be sure that they cannot/do not access the internet.

**Comment by Spectre5** [comment]
As for the red light, mine do not flash.  I think since they are connected to a wifi, they do not flash.

**Comment by esev** [comment]
I'm not able to get mine to stop flashing red periodically when they are on a non-internet VLAN. :(

I've tried `basicevent.ReSetup(Reset=1)`, `basicevent.ReSetup(Reset=3)` and `basicevent.ReSetup(Reset=2)` and then run through the `setup` to reconnect to my wifi.

`metainfo.GetExtMetaInfo` is able to show some more device details.
```python
meta_info = device.metainfo.GetExtMetaInfo()['ExtMetaInfo'].split("|")
meta_info = {
    'CurrentClientState': meta_info[0],
    'IceRunning': meta_info[1],
    'NatInitialized': meta_info[2],
    'LastAuthVal': meta_info[3],
    'Uptime': meta_info[4],
    'CurFWUpdateState': meta_info[5],
    'UTCTime': meta_info[6],
    'HomeID': meta_info[7],
    'RemAccessEnable': meta_info[8],
    'Model': meta_info[9],
}
```

The `HomeID` and `RemAccessEnable` parameters look like might be related to the cloud settings. A `basicevent.ReSetup(Reset=3)` does clear `RemAccessEnable`, but the device still tries to connect to the cloud and flashes red when I disconnect it from the internet.

**Comment by Spectre5** [comment]
I saw the HomeID too.  What if you do a factor reset through the app, then use pywemo's `setup` method to connect it to your home network.  Or did you try that?  That is effectively how mine are setup and they never flash nor give me issues.  I have not yet put them on a non-internet VLAN though, which is something I still intend to do.

**Comment by esev** [comment]
I think the App's factory reset uses the local UPnP API.

![Screenshot_20210131-161755](https://user-images.githubusercontent.com/289218/106402880-9b0bd480-63e0-11eb-995a-d927535c8e56.png)

I need to setup an Android VM like you did to make this easier! I'm not able to press that button if I'm not on the same Wifi network. The device is on my IoT wifi network, and I've got my access point set to not allow devices on that network to be able to communicate with each other (they can only talk to things on my ethernet network). So my phone won't be able to talk to the device either after switching to the IoT network.  Fail. :(

I'll try with a USB ethernet adapter on my phone.

**Comment by Spectre5** [comment]
Yes, you can try to setup the VM or else temporarily take it off that IoT network just to reset it.

But yes, I believe that those 3 options you have there are the same as the `reset(True, False)`, `reset(False, True)`, and `reset(True,True)` methods in pywemo.  Note that you actually have the wong reset codes mentioned above.  Form the pywemo source, the actual codes are below.  So `Reset=2` is the "Factory Restore".  But clearly wifi only ("Change Wifi" is actually "Reset=5".

```python
        if data and wifi:
            LOG.info('Clearing data and wifi (factory reset)')
            result = action(Reset=2)
        elif data:
            LOG.info('Clearing data (icon, rules, etc)')
            result = action(Reset=1)
        elif wifi:
            LOG.info('Clearing wifi information')
            result = action(Reset=5)
```

**Comment by esev** [comment]
There are actually 4 reset states (I'm looking at the firmware in Ghidra).

1 = Clear data
2 = Factory reset
3 = Reset remote
5 = Clear wifi

**Comment by Spectre5** [comment]
Ah, so the `Reset=3` is one I'm unaware of then.  That did not get triggered when I pressed any of those 3 buttons in the app.  The way I figured out those others was via the app in a VM and then using wireshark to see what was communicated.

**Comment by Spectre5** [comment]
I haven't used Ghidra but now I'm really interested in it haha

**Comment by Spectre5** [comment]
I was worried about the flashing too if I had them only on my wifi but not connected to the cloud.  Now I'm worried that maybe they are still talking to the cloud since I don't have them on an IoT wifi without internet access yet (on the todo list).  I'll need to test that out, but it would certainly be annoying for me too if it flashed due to that.

**Comment by Spectre5** [comment]
You were able to use pywemo to set them up though?  To connect back to the wifi after resetting them?

**Comment by esev** [comment]
lol - I was impressed with Ghidra. After unpacking the firmware (using binwalk) Ghidra was able to open the linux binaries just fine. There are a lot of logging statements in the code, so it's relatively easy to follow. There used to be a UPnP command there to control the LEDs on the device, but they've removed the functionality from the method. That would have been neat to use as some sort of notification indicator :)

> Now I'm worried that maybe they are still talking to the cloud since I don't have them on an IoT wifi without internet access yet (on the todo list).

I don't know what the default setting for this is, but I've run `basicevent.setAutoFWUpdate(enableAutoUpdate=0)` on mine just in case.

AFAICT, if you run that `metainfo.GetExtMetaInfo` command, the `RemAccessEnable` field from the result can tell if you're still connected to the cloud.

> You were able to use pywemo to set them up though? To connect back to the wifi after resetting them?

Yes, it works beautifully. Thanks for this!

**Comment by Spectre5** [comment]
One of the things I'd still like to add to pywemo is a contributing file where a main portion of it would really be discussion on the various tools with some simple/quick get up and running instructions.  For example, creating the VM (which android was used, which APK and why), etc.  Ghidra would be another good one as well (would love a quick run-down!) as some other tools like netdisco.  This would be useful for someone new trying to understand how the devices work, but also as a good reference for my future self!

As for `setAutoFWUpdate`, I've done the same :rofl: even though I have no idea what it does.  I hope (assume!) that zero is off...

I spent some time with the `explain` method and trying to look into most of the various methods there.  But having the firmware like you have is totally awesome.  It would be great to add to the previously mentioned contributing guide some information on what all of the returned data is for `GetExtMetaInfo`, as well as others.  I had tried to decipher (guess) what each field was in that method and others.

I *am* seeing the result of `RemAccessEnable` is 1 on my devices, so I suppose it is still connected to Belkin.  Which is weird since I've done a "factory reset" multiple times since removing the app from the phone entirely.  I guess it isn't truly a factor reset then, as my interpretation of that would be erasing EVERYTHING.  Now its pushing me to go get that IoT wifi setup that I've been putting off.  But I definitely want to know if you find a solution for the light then, as that would drive my wife crazy enough that she might make me put them back on the regular network...

**Comment by Spectre5** [comment]
What do you suppose `NatInitialized` is?  Mine are 1 for all devices except 1 of them that show -1.

You should make a PR to add the contribution guide with this info and tool information so we can extend it with whatever we know.

**Comment by esev** [comment]
I'm not sure on 'NatInitialized'. From my digging 'Nat' & 'Remote' & 'Cloud' all seem very much related. I'm just not sure how they are related yet. There is a `natClient` binary in the firmware. I have't dug into that yet. I've focused mostly on the UPnP stuff in `libUPnPHndlr.so`

> You should make a PR to add the contribution guide with this info and tool information so we can extend it with whatever we know.

That's a good idea!

**Comment by esev** [comment]
As for setAutoFWUpdate, 0 does indeed seem to be off.

When `enableAutoUpdate` is 0, a parameter named `fwup_disabled` gets set to 1. When `enableAutoUpdate` is non-zero, that `fwup_disabled` parameter gets set to 0.

**Comment by esev** [comment]
> I am seeing the result of RemAccessEnable is 1 on my devices, so I suppose it is still connected to Belkin. Which is weird since I've done a "factory reset" multiple times since removing the app from the phone entirely.

When I use `basicevent.ReSetup(Reset=3)`, and I have the internet disconnected (I'm just using iptables to block the one IP on my IoT lan), `RemAccessEnable` does switch to '0'. However, when I give the device access to the internet again, it still connects to the cloud service. It then switches `RemAccessEnable` to `1` and starts reporting a different value for `HomeID`. At this point I'm no longer able to use the WeMo app to communicate with the device, but it is still connected to the cloud. Doing a `basicevent.ReSetup(Reset=2)` at this point (and re-running through the setup) brings back the `HomeID` to the original value and allows the app to work with the device again.

I think maybe Belkin is maintaining a mapping between the device ID (maybe serial number) and the `HomeID` that it should be assigned to within their cloud servers. That could explain why `basicevent.ReSetup(Reset=2)` is able to restore the original `HomeID`.

**Comment by Spectre5** [comment]
Interesting.  Anytime remote access is zero though and it can't phone home, the lights flash?

**Comment by Spectre5** [comment]
I wonder if one of these other methods on the device can help somehow, not sure which though.

**Comment by esev** [comment]
> I wonder if one of these other methods on the device can help somehow, not sure which though.

hehe. This is exactly why I've been looking in Ghidra :)

**Comment by esev** [comment]
> Interesting. Anytime remote access is zero though and it can't phone home, the lights flash?

I'm not sure yet exactly what causes `NatInitialized` & `RemAccessEnable` to be 0. I think the `Reset=3` causes `RemAccessEnable` to be 0 temporarily, but it might get re-enabled later when the device connects to the cloud again.

**Comment by Spectre5** [comment]
Have you tried a hardware reset?  Most (all?) Of the devices have a hardware reset method.

**Comment by esev** [comment]
Yes. Tried that, and also got an ethernet connection on my phone and reset it through the app. The device still tries to maintain a connection to the cloud and flashes red when there is no internet. :(

Oddly enough, even with using the factory restore button in the app, my device still ends up with the same HomeID when it reconnects back with the cloud - even though I can no longer see it in the app.

**Comment by Spectre5** [comment]
I've seen some of these same things as well, where my app didn't show the device.  That made me assume that it was not connected to the cloud and since I had no blinking light, I figured that being connected to wifi was enough to disable that light.  Clearly I was wrong though.  I did find it suspicious that the homeID was changed and then changed back to the old/original one (I saw that too!).  Hm...going to have to look into this more for sure, I'll check out Ghidra soon to help better understand these details too!

**Comment by Spectre5** [comment]
oops, didn't mean to re-open it

**Comment by esev** [comment]
Ah ha! The red blinking light seems to go away when ICMP is allowed (to `heartbeat.xwemo.com`). And it needs to connect to the local DNS server to lookup the `heartbeat.xwemo.com` domain.

It still tries to connect to the cloud, but with everything but ICMP blocked it cannot actually connect to the cloud. And no red blinking light. Win!

**Comment by Spectre5** [comment]
Very nice, thanks!  Another thing worth adding to the contributing guide or maybe the README itself.  I'll definitely follow this when I move mine over, thanks for all the digging!

**Comment by esev** [comment]
https://www.scip.ch/en/?labs.20160218 has some more data about how the devices get connected to the cloud (RemoteAccess API).

**Comment by Spectre5** [comment]
Oh ya, I did come across that too when I wrote the reset/setup code, but I'd forgotten that it had that discussion in there.

Is there a way to access its internal log?  There is a `GetLogFileURL` action but the URL it provides returns a 404.

Also, have you looked at all at the `device.remoteaccess.RemoteAccess` action?

**Comment by Spectre5** [comment]
There is also a `SetLogLevelOption` action, so maybe the log is 404 since it isn't turned on.  I haven't tried messing with it.

My two lightswitches, by the way, do not have the `setAutoFWUpdate` action.  Do all of yours have it?  I last updated my firmware at the same time, but I think these lightswitches are first gen, or maybe second.

**Comment by esev** [comment]
I haven't been able to find anything that writes to the PluginLogs.txt path yet. :(

I was able to call the `device.remoteaccess.RemoteAccess` action the way they describe in the Communication Analysis post. It looks like that is what registers the device on the cloud service.

> My two lightswitches, by the way, do not have the setAutoFWUpdate action. Do all of yours have it?

I don't have my V1 lightswitch installed at the moment. All of mine are the V2 and have firmware version `WeMo_WW_2.00.11563.PVT-OWRT-LIGHTV2`. These all have the setAutoFWUpdate action. This is also the only firmware version that I have downloaded, and is the one that I've been looking at in Ghidra.

**Comment by Spectre5** [comment]
The `RemoteAccess` action cannot un-register the device though?  That's what I was looking for.

Looks like my lightswitch is a v1 with firmware `WeMo_WW_2.00.11408.PVT-OWRT-LS`

**Comment by esev** [comment]
> The RemoteAccess action cannot un-register the device though? That's what I was looking for.

I've been looking for just that too. Unfortunately Ghidra's decompiler isn't working on the RemoteAccess method, and my MIPS assembly skills are lacking :) But, it's pretty easy to see the names of the functions that are being called, and I don't see anything obvious in that action that would disconnect from the cloud. It looks like the RemoteAccess action is processing the action parameters and then making a call to the cloud service to register the device. It waits for a response from the cloud service and then returns back a bunch of parameters. It does a bunch of error checking on the parameters too, but other than that not much else.

**Comment by esev** [comment]
It really looks like the cloud cannot be disabled. :(

`libRemoteAccess.so` looks like the binary with the cloud connection logic. There is a method inside called `initCoreThreads`. That appears to be the method that starts all the threads that interact with the cloud service. I don't see a check anywere that would prevent initCoreThreads from running, and I don't see any checks inside initCoreThreads that prevents it from starting the cloud-related threads.

I also thought about trying to change the host names that the device uses when connecting to the cloud, but those appear to all be hard-coded into the binary.

Tomorrow I might try seeing what happens when the DHCP server doesn't provide the device with a default gateway. I suspect that will cause the red light to flash again though.

**Comment by esev** [comment]
When the DHCP server doesn't provide a default gateway, the device continually reboots and flashes the white LED (same LED pattern as it does when you restore power to it). So that option doesn't work.

I then tried configuring the DHCP server to not respond with a DNS server. That works! You still need to allow ICMP (to 8.8.8.8) to avoid the red-flashing LED, but if the device isn't provided with a DNS server then it never connects to the cloud.

**Comment by Spectre5** [comment]
It could, potentially, have a hardcoded DNS, probably 8.8.8.8.  A lot of IoT devices ignore DNS settings and use a hardcoded value, if it is reachable, and then only uses the DHCP provided value if the hardcoded one isn't reachable.

**Comment by esev** [comment]
There is a hardcoded `8.8.8.8` for sending an ICMP connectivity test. But I don't see a hardcoded 8.8.8.8 for the DNS settings. That could, of course, change with future firmware releases.

**Comment by esev** [comment]
I see this now, for `metainfo.GetExtMetaInfo`, with no DNS server configured.

```
{
  'CurrentClientState': '1',
  'IceRunning': '0',
  'NatInitialized': '0',
  'LastAuthVal': '0',
  'Uptime': '1:38:49',
  'CurFWUpdateState': '4',
  'UTCTime': '946690719',
  'HomeID': 'NNNNNN',  # Same six-digit value it has had all along
  'RemAccessEnable': '1',
  'Model': 'Dimmer'
}
```

**Comment by Spectre5** [comment]
Gotcha ok

**Comment by Spectre5** [comment]
All of this is useful stuff to add to that contribution guide too, or maybe more appropriately something like a "WEMO_GUIDE.md" or "HOWTO.md" file.

**Comment by Spectre5** [comment]
How did you grab the firmware to use in Ghidra?

**Comment by esev** [comment]
I watched the network traffic that happened the last time the device updated. It downloads the firmware over http (not https) so it is possible to capture the url.

Send me a PM on the [HA chat](https://discord.gg/5EME9fre), or email me using the email in the 'git log'. I don't know if I should share the URL publicly.

**Comment by esev** [comment]
I started a few Wiki pages to document things.

- [Local Interface](https://github.com/pavoni/pywemo/wiki/Local-Interface)
- [WeMo Firmware](https://github.com/pavoni/pywemo/wiki/WeMo-Firmware)

**Comment by esev** [comment]
And I added another page with some details on the [cloud service](https://github.com/pavoni/pywemo/wiki/WeMo-Cloud), including some ways to disconnect from the cloud.

**Comment by Spectre5** [comment]
awesome, thanks! I'll and expand as needed too.  I think the wiki is a good place for this info
