### ISSUE TITLE
Maker sensor status

### ISSUE THREAD

**Issue by Kokicha** [pywemo/pywemo#18]
Can you help me to understand how I could use this code to obtain the status (change) of a sensor connected to a Wemo maker?

**Comment by pavoni** [comment]
To check a single shot status use the code below.

Note '1' means 'not triggered'

You'd need to poll to look for a status change.

```
>>> devices = pywemo.discover_devices()
>>> devices
[<WeMo Maker "Rain Sensor">, <WeMo Maker "gate toggle">]
>>> devices[0]
<WeMo Maker "Rain Sensor">
>>> devices[0].sensor_state
1
>>> devices[0].maker_params
{'hassensor': 1, 'switchstate': 0, 'sensorstate': 1, 'switchmode': 0}
```

**Comment by Kokicha** [comment]
Thanks for that.  Works well.   One other question though - I have a 5 Wemo devices with the maker sensor that I want to monitor being 5th in the list (device #4).  I assume this is the order that wemos are found as occasionally the order changes or one device is not found. When this happens it breaks the code as my maker is no longer device #4.

**Comment by pavoni** [comment]
You can use Python filtering to do this to either seatch by name, or class. For example:-

```
>>> import pywemo
>>> devices = pywemo.discover_devices()
>>> devices
[<WeMo Maker "gate toggle">, <WeMo Insight "Kettle">, <WeMo Switch "Coffee Machine">, <WeMo Maker "Rain Sensor">, <WeMo Maker "Skylight Open">, <WeMo Maker "Skylight Close">, <WeMo Maker "blind toggle">, <WeMo Switch "Hi Fi Power Amp">, <WeMo Insight "Hi Fi Preamp">, <WeMo Insight "Hi Fi Sources">, <WeMo Maker "Hi Fi Systemline Sensor">]
>>> makers = [x for x in devices if isinstance(x, pywemo.ouimeaux_device.maker.Maker)]
>>> makers
[<WeMo Maker "gate toggle">, <WeMo Maker "Rain Sensor">, <WeMo Maker "Skylight Open">, <WeMo Maker "Skylight Close">, <WeMo Maker "blind toggle">, <WeMo Maker "Hi Fi Systemline Sensor">]
>>> devices[0].name
'gate toggle'
>>> [x for x in devices if x.name == "blind toggle"]
[<WeMo Maker "blind toggle">]
```

**Comment by Kokicha** [comment]
Thanks very much. My Python skills are limited but that's working very reliably for me now. Excellent!
