### ISSUE TITLE
Discusson: poetry.lock file

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#181]
This is just meant as a quick discussion.  Why does pywemo commit the poetry.lock file?  I understand that it provides deterministic builds, but I think it is meant more for applications (final products), less so for libraries.  I see pywemo as a library.

In general, poetry does suggest that you commit it [in their docs](https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control), however it also indicates in that section that "For libraries it is not necessary to commit the lock file."

**Comment by pavoni** [comment]
I'm certainly not an expert. And even now it isn't even working the way I'd expect (the recent release built fine on my local machine - and failed on github until I updated the various library versions).

This probably means something is missing in poetry.lock.

My main aim is to make sure the build on github is the same as my local build - and I think the lock file would help, rather than hinder this!

Views from experts very welcome!

**Comment by Spectre5** [comment]
Ya, I'm no expert with poetry either.  That said, my understanding is that if the poetry.lock file is present, poetry should use it exactly (which is your goal here), and if it is not present, then it uses what is in the pyproject.toml file.  If they differ, then it complains (gives a warning).  If you lock the pyproject.toml file to an exact version (use == instead of ^ or another variation of versioning), then it would use those exact versions anyways, even without the lock file.  I think that in general though, libraries don't usually try to lock to really specific versions and usually want to be as "open" as possible to different versions.

I just did a test --- I cloned this library to a new directory and ran the `build.sh` script, then activated the environment.  The poetry version is 1.1.4 (it uses `pip install poetry` in `build.sh`, so the latest version will be put into the virtual environment).  Then if I simply run `poetry lock`, it results in a different lock file (may lines changed)!  However, it appears that the file is essentially the same, but that this newer version just orders it differently.  The newer one is more reasonable, really, since the name and version are listed first.  As a quick example, here is the first package in each:

Current master:

    [[package]]
    category = "dev"
    description = "Atomic file writes."
    name = "atomicwrites"
    optional = false
    python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
    version = "1.4.0"

updated with `poetry lock`:

    [[package]]
    name = "atomicwrites"
    version = "1.4.0"
    description = "Atomic file writes."
    category = "dev"
    optional = false
    python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

There are 2 libraries with different versions too (`package` and `py`), here is one on master:

    [[package]]
    category = "dev"
    description = "Core utilities for Python packages"
    name = "packaging"
    optional = false
    python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
    version = "20.7"

and after the re-locked:

    [[package]]
    name = "packaging"
    version = "20.8"
    description = "Core utilities for Python packages"
    category = "dev"
    optional = false
    python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

**Comment by Spectre5** [comment]
It's certainly weird that your last build was fine locally, but failed on github.  I wonder if that is related to the different versions of python tested?  Maybe whatever local version of python you use was fine but since the automated tests use multiple version, it doesn't end up being identical to what you have.  Maybe that is why the lock file isn't recommended for a library, but is for a final "application" which would often be tied to a specific python version too.

I'm just guessing here though, I don't know poetry well enough either.  Would certainly like to hear the input of someone more experienced.

**Comment by pavoni** [comment]
Are you comfortable that your PR covers this issue?

**Comment by Spectre5** [comment]
I guess this discussion was just trying to understand if we even should commit the lock file or not.  I'm fine with leaving it, but I just see that half the PR I make ends up changing it.  Obviously if a dependency is added (or removed), then the lock file will change.  But sometimes it seems to change even when no dependencies were touched.  You can close this issue though, I think.
