### ISSUE TITLE
[Discussion] Use lxml.etree instead of cElementTree?

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#197]
When I upgraded the device.py and service.py files, I added lxml as a dependency, which is already installed on HA as well anyway.  Is it worthwhile to change the `cElementTree` code within the rest of the project to use lxml.etree as well?  lxml is generally a little faster and offers some more advanced features.  With that said, I can't image it would be any noticeable real-world difference with the tiny size of xml files using with Wemo devices and we probably don't need any of the extra features.  The other minor benefit would be pywemo using the same ElementTree implementation as those two underlying files.  I'm still not sure if it is worthwhile though, what do you guys think @pavoni and @esev?

**Comment by esev** [comment]
> The other minor benefit would be pywemo using the same ElementTree implementation as those two underlying files.

I think having only one XML implementation would be beneficial. I agree with you that there isn't going to be a noticeable speed difference. So, maybe treat this as low-priority? [I'm not sure what other changes you have planned]

**Comment by Spectre5** [comment]
I'll probably look at it when I have some time, but I'd agree that it is low-priority and I'm not sure when I'll look into it yet.

**Comment by Spectre5** [comment]
Created a PR to switch to lxml, but I haven't tested it much yet
