### ISSUE TITLE
[Development] Add a pre-commit hook

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#199]
Making this issue/discussion mainly as a reminder.  We may want to look into running the various checks from the `build.sh` file as a pre-commit hook.  It could be installed as part of the build.sh file as well (or a new, separate file that installs poetry and the pre-commit hook only).

**Comment by pavoni** [comment]
Would be happy with this if you wanted to put together a PR.

I think this works well in the HA dev environment.

**Comment by Spectre5** [comment]
Yup I will put one together later today!
