### ISSUE TITLE
Travis CI Build Badge (outdated)

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#216]
When clicking the build badge, it goes here:
[https://travis-ci.org/pavoni/pywemo](https://travis-ci.org/pavoni/pywemo)

There are a few problems:

- This appears to be outdated by 4-5 months.  The branches are 0.4.X and master was last updated 5 months ago.
- There is a message at the top of the page that we need to update to `.com`: "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information."

It looks like travis-ci isn't even used anymore anyway with pywemo, so is there a new badge we can replace it with to get the current build status of master shown?

**Comment by pavoni** [comment]
Should now be fixed.

**Comment by Spectre5** [comment]
Great, thanks!
