### ISSUE TITLE
[Discussion] Hound

### ISSUE THREAD

**Issue by Spectre5** [pywemo/pywemo#232]
@pavoni, does the hound ci actually do anything?  In the YAML config file, python is disabled.  So I assume it is only being used to check bash files syntax (doesn't support reStructuredText)?
https://github.com/houndci/hound

**Comment by pavoni** [comment]
I think it’s a ghost.

I have removed two web hooks.

**Comment by Spectre5** [comment]
You removed the only two web hooks it used, or are there others?  Should it be removed then or is it still used?

**Comment by pavoni** [comment]
Hound and the old CI.

Where else does it need to be removed?

**Comment by Spectre5** [comment]
Just the hound.yml file in the top directory then!
