### ISSUE TITLE
Wifi setup does not work for WSP080 & WSP090

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#237]
Both the [WSP080](https://www.belkin.com/us/p/P-WSP080/) & [WSP090](https://www.belkin.com/us/p/P-WSP090/) devices do not work with the WiFi setup code.

```python
print(device.setup('IoTnetwork', '19characterlongpassword'))
Original exception was:
Traceback (most recent call last):
  File "reset.py_", line 62, in <module>
    print(device.setup('IoTnetwork', '19characterlongpassword'))
  File "pywemo/pywemo/ouimeaux_device/__init__.py", line 476, in setup
    return self._setup(*args, **kwargs)
  File "pywemo/pywemo/ouimeaux_device/__init__.py", line 653, in _setup
    raise ShortPassword(
pywemo.ouimeaux_device.ShortPassword: Password is too short (Wemo requires at least 8 characters).
```
```
DEBUG:pywemo.ouimeaux_device:network status after 5.68 seconds: 2
DEBUG:pywemo.ouimeaux_device:network status: 2
DEBUG:pywemo.ouimeaux_device:close status: CloseSetup action not available
```

Both devices stay in "Access Point" mode (initial setup mode where they act as a WiFi access point) and do not join the network that is being configured. Both of these devices appear to be based on a different firmware platform (`RTOS`) than most other devices (`OWRT`).

**Comment by Spectre5** [comment]
Huh.  Looks like the network status codes are different for the RTOS firmware devices, and potentially some of the codes used in other functions too.  Can you send the output of "explain" for one of these?  Or maybe we have the details in a vcr file already, I haven't looked.

**Comment by esev** [comment]
WSP090 explain:
```
WiFiSetup
---------
  GetApList(ApList)
  GetNetworkList(NetworkList)
  ConnectHomeNetwork(ssid, auth, password, encrypt)
  GetNetworkStatus(NetworkStatus)

smartsetup
----------
  PairAndRegister(PairingData, RegistrationData, PairingStatus)
  GetRegistrationData(Authorization, X-Wemo-ALT-Token, deviceId, uniqueId, friendlyName, groupId, smartDeviceUniqueId, reRegister, provisionedBy, timeStamp)
  GetRegistrationStatus(RegistrationStatus, StatusCode, groupId, deviceId, deviceToken, timeStamp)

metainfo
--------
  GetMetaInfo(MetaInfo)
  GetExtMetaInfo(ExtMetaInfo)

timesync
--------
  TimeSync(UTC, TimeZone, dst, DstSupported)

basicevent
----------
  SetBinaryState(BinaryState, Duration, EndAction, UDN, CountdownEndTime, deviceCurrentTime)
  GetBinaryState(BinaryState)
  SimulateOverTemp(overTemp, overTempStatus)
  GetFriendlyName(FriendlyName)
  ChangeFriendlyName(FriendlyName)
  GetIconVersion(IconVersion)
  ReSetup(Reset)
  setHKSetupState(HKSetupDone)
  getHKSetupState(HKSetupDone)
  GetHKSetupInfo(HKSetupKey, HKSetupCode)
  removeHomekitData()
  SetAwayRuleTask(EnableAwayTask, RuleID, actionStatus)
  NotifyManualToggle(UDN, ManualToggle)
  GetSimulatedRuleData(UDN, RuleData)

rules
-----
  GetRulesDBPath(RulesDBPath)
  StoreRules(ruleDbVersion, processDb, ruleDbBody, errorInfo)

deviceinfo
----------
  GetInformation(Information)
  GetDeviceInformation(DeviceInformation, Payload, HKSetupState, ProvisionedBy)

firmwareupdate
--------------
  UpdateFirmware(NewFirmwareVersion, ReleaseDate, URL, Signature, DownloadStartTime, WithUnsignedImage)
  GetFirmwareVersion(FirmwareVersion)

manufacture
-----------
  GetManufactureData(ManufactureData)
```

WSP080 vcr: https://github.com/pavoni/pywemo/blob/master/tests/vcr/tests.ouimeaux_device.test_switch/WEMO_WW_4.00.20101902.PVT-RTOS-SNSV4.yaml

**Comment by Spectre5** [comment]
Looks like the connect home network doesn't take a channel argument here...so something is definitely different!

**Comment by esev** [comment]
I'm pretty sure the `<new_algo>1</new_algo>` in setup.xml is going to be related to this. It looks like the algorithm for generating the encrypted wifi password may have changed.

Note to self: Remember to check if the [Insight devices](https://github.com/pavoni/pywemo/blob/a66e95e3eaf05bf04b9cdcdc1901fe72282892bf/tests/vcr/tests.test_subscribe/WeMo_WW_2.00.11408.PVT-OWRT-Insight.yaml) work too. `<binaryOption>1</binaryOption>`

**Comment by esev** [comment]
Got it working for WSP080 & WSP090. It needed two changes.

1. There is an extra string that gets tacked onto the end of `keydata` (I'm not sure where we should store this string - just add it to the code directly?)
2. The device expects the base64 encoded string directly, it doesn't require the two hexadecimal length parameters to be tacked onto the end.

**Comment by Spectre5** [comment]
Interesting, nice investigation!

**Comment by Spectre5** [comment]
As for the extra string to add, I think we should probably store it in a global constant, with a comment that certain devices need it appended.  Other devices, now or in the future, may have different constants added.  And I guess we need to add logic to select which "style" to use depending on the device, or on the firmware of the device.

Did you still send the channel?  I guess that maybe you can still send it and then it will just be ignored by the device then?  Since your signature doesn't apparently include it

**Comment by Spectre5** [comment]
I think we should make a list of everything different (known, anwyay) with the rtos devices compared to the owrt ones.  If there are enough (consistent) differences, then it may be worth removing those unique parts from the `Device` class (so that it only has the common parts) and then making an RTOS and OWRT specific class that inherit from `Device`, or perhaps the unique parts could be added as a mixin when a device is created.  The password stuff would be easy to do this with, I just hope that the rtos and owrt devices are consistent with themselves.  But we should make a list of other differences we may need to account for too

**Comment by RussellAult** [comment]
I just ran into the same problem. @esev do you have a patch or PR you can share to point me in the right direction??

**Comment by esev** [comment]
Hi @RussellAult, PR #267 should work. Could you test it on your device?

**Comment by RussellAult** [comment]
@esev Amazing! Thanks for this! Here's my test results with a WSP090:

- `get_state()` and `toggle()` both worked exactly as expected, both before and after setup
- `setup()` was successful (in that the WSP090 did connect to the Wi-Fi network) but threw the following error on completion:
```
Wemo device likely connected to "SSID-REDACTED", but should be verified (CloseSetup returned "CloseSetup action not available").
('1', 'CloseSetup action not available')
```

**Comment by Spectre5** [comment]
That is probably fine as some devices (even the non-rtos ones) don't have this method.  To be honest, I don't know what this method even does, but I saw that it was called on my wemo mini when I set it up with the app, so we call it in this setup code but ignore it if it doesn't exist.  We could probably be smarter with this and instead check if the method actually exists before we try calling it.  As long as it did connect to the network though, you should be good.

However --- you said that get_state and toggle worked ever **before** you ran setup?  The device must have already been connected to your network then (probably through the wemo app).  The point of the setup method is really to connect the device to your network wihtout the Wemo app --- if you already use the wemo app to connect your device, then you really don't need to the setup method at all.  Or...perhaps you meant simply that those methods worked when you connected to the devices own locally broadcast network (i.e. just before calling setup and not on your home network)...in that case, ignore this last paragraph.

**Comment by Spectre5** [comment]
You can use the `explain` method to see if `CloseSetup` even exists on your wemo device.

**Comment by RussellAult** [comment]
> 
> 
> {...} Or...perhaps you meant simply that those methods worked when you connected to the devices own locally broadcast network (i.e. just before calling setup and not on your home network)...

👍 This is it exactly

**Comment by esev** [comment]
Awesome! Thanks for testing. I'll merge #267.

**Comment by RussellAult** [comment]
> 
> 
> You can use the `explain` method to see if `CloseSetup` even exists on your wemo device.

For what it's worth, there's nothing in the output of `explain()` for my WSP090 called `CloseSetup`

**Comment by Spectre5** [comment]
Gotcha, ok!  I'll make a new PR soon to change the setup method to check for the close setup method!

**Comment by RussellAult** [comment]
Thanks again for all the help!
