### ISSUE TITLE
pywemo fails to work correctly with HA 2021.3.0

### ISSUE THREAD

**Issue by ausil** [pywemo/pywemo#253]
HA 2021.3.0 upgraded pywemo to 0.6.3
2021-03-04 00:29:43 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of pywemo==0.6.3

When starting up it fails with 
2021-03-04 00:34:46 ERROR (MainThread) [homeassistant.setup] Setup failed for wemo: unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 491, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/wemo/__init__.py", line 4, in <module>
    import pywemo
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/__init__.py", line 4, in <module>
    from .discovery import discover_devices, setup_url_for_address
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/discovery.py", line 9, in <module>
    from . import ssdp
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/ssdp.py", line 12, in <module>
    from .ouimeaux_device.api.long_press import VIRTUAL_DEVICE_UDN
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/ouimeaux_device/__init__.py", line 21, in <module>
    from .api.service import REQUESTS_TIMEOUT, Service, Session
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/service.py", line 28, in <module>
    class Session:
  File "/srv/homeassistant/lib/python3.9/site-packages/pywemo/ouimeaux_device/api/service.py", line 56, in Session
    retries = urllib3.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

**Comment by ausil** [comment]
updating urllib3 to a new enough version has fixed the issue, you should make sure to require a new enough version

**Comment by esev** [comment]
Fixed in 0.6.3

See also:
- https://github.com/pavoni/pywemo/issues/248
- https://github.com/home-assistant/core/issues/47334

Even though it has been fixed, let's keep this issue open for a bit to improve discoverability of the fix.

**Comment by ausil** [comment]
it is not fixed in 0.6.3 after installing it is when things broke, you need to add a versioned dependency on urllib3 to a version that supports allowed_methods

**Comment by esev** [comment]
Hey @Spectre5, is there a way to make sure the change from #249 is reflected in the 0.6.3 package?

**Comment by pavoni** [comment]
As far as I can see this looks right
https://github.com/pavoni/pywemo/compare/0.6.2...0.6.3

**Comment by esev** [comment]
pipdeptree looks right also.

```
pywemo==0.6.3
  - ifaddr [required: >=0.1.0, installed: 0.1.7]
  - lxml [required: >=4.6,<5.0, installed: 4.6.2]
  - requests [required: >=2.0, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2020.12.5]
    - chardet [required: >=3.0.2,<5, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.3]
  - urllib3 [required: >=1.26.0, installed: 1.26.3]
```

`allowed_methods` is in 1.26.0 https://github.com/urllib3/urllib3/blob/1.26.0/src/urllib3/util/retry.py

**Comment by esev** [comment]
It it possible that the python interpreter had already loaded an older version of `urllib3` before the `pywemo` package was updated? I'm not very familiar with what Home Assistant is doing here:

```
HA 2021.3.0 upgraded pywemo to 0.6.3
2021-03-04 00:29:43 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of pywemo==0.6.3
```

**Comment by Spectre5** [comment]
Yup, the *tar.gz file on PyPI has the correct dependency:

```
install_requires = \
['ifaddr>=0.1.0', 'lxml>=4.6,<5.0', 'requests>=2.0', 'urllib3>=1.26.0']
```

That said, `pip` doesn't strictly enforce versions, so perhaps @ausil should check with `pip check`?  Maybe another library installed requires a version less than 1.26.0 and there is a conflict?  ~If the wheel is used, there is no version dependency information in the wheel file, so I'm not exactly sure how that works...~ The wheel has the right version too:

```
Requires-Dist: ifaddr (>=0.1.0)
Requires-Dist: lxml (>=4.6,<5.0)
Requires-Dist: requests (>=2.0)
Requires-Dist: urllib3 (>=1.26.0)
```

**Comment by esev** [comment]
This seems to be what Home Assistant is doing
https://github.com/home-assistant/core/blob/43474762b24e285bc525d9ffa09c6f7658525353/homeassistant/util/package.py#L64

I could be wrong here, but i'm pretty sure if another Home Assistant component had already loaded the existing `urllib3` before the upgrade happened, the python runtime would not re-import a new version of `urllib3`. So then `pywemo` would be using the wrong `urllib3` version.

**Comment by Spectre5** [comment]
Wheel is good too (updated previous comment)

**Comment by esev** [comment]
@ausil does it work after a restart?

**Comment by Spectre5** [comment]
`pip` should then update `urllib3` before installing `pywemo`, right?  Unless perhaps there is a conflict somewhere else and then it just leaves it as-is.

I think @ausil got his fixed, sounds like he manually updated `urllib3` to a newer version.  The question is why the install didn't do that automatically, as `pip` should have.

**Comment by Spectre5** [comment]
Maybe when `pywemo` was installed, it did upgrade the dependency for `urllib3`, but then another library was installed/upgraded afterwards with a requirement less than `1.26.0`?  In that case, `pip` will downgrade to match the latest installed/upgraded package from my experience.  So I still suspect that another library requires a lower version.  I'm not sure of a really easy way to find that when there are so many potential dependencies with HA, but we could potentially reduce it to a subset of them based on what @ausil has installed.

**Comment by ausil** [comment]
I only got it working by running `pip3 install --upgrade urllib` as urllib3-1.25.11 was installed. after upgrading urllib3 and restarting hass did everything work again.

**Comment by ausil** [comment]
```
grep -r urllib3 /srv/homeassistant/lib/python3.9/|grep Dist
/srv/homeassistant/lib/python3.9/site-packages/botocore-1.19.9.dist-info/METADATA:Requires-Dist: urllib3>=1.25.4,<1.25.8; python_version=='3.4'
/srv/homeassistant/lib/python3.9/site-packages/botocore-1.19.9.dist-info/METADATA:Requires-Dist: urllib3>=1.25.4,<1.26; python_version!='3.4'
/srv/homeassistant/lib/python3.9/site-packages/pywemo-0.6.3.dist-info/METADATA:Requires-Dist: urllib3 (>=1.26.0)
/srv/homeassistant/lib/python3.9/site-packages/requests-2.25.1.dist-info/METADATA:Requires-Dist: urllib3 (<1.27,>=1.21.1)
```

**Comment by Spectre5** [comment]
So botocore conflicts here.  I wonder if they can allow newer versions, does that library still work properly?

**Comment by ausil** [comment]
I do not directly use botocore anywhere that I know of, it looks like it is pulled in for the cloud and mobile client which I do use. boto3 requires an old version of botocore which may be part of the problem `boto3 1.16.9 requires botocore<1.20.0,>=1.19.9, but you'll have botocore 1.20.21 which is incompatible.` so I can not update. I will have to double-check what is working correctly

**Comment by ausil** [comment]
It appears everything is working correctly.

**Comment by esev** [comment]
Looks someone else is having trouble with this in https://github.com/home-assistant/core/issues/47334

I wonder why Home Assistant installs pywemo v0.6.3 without having the dependencies being met (assuming that's what is happening here)?

**Comment by Spectre5** [comment]
Pip really isn't great at handling conflicts.  I'm fairly certain that what is happening is that pywemo gets installed and the later another library, like botocore, is installed and pip then downgrades urllib3 to meet the requirement of the latest installed library.

**Comment by Spectre5** [comment]
Here is a demonstration of that in a fresh venv.  I don't see any way around this except lowering the requirement in pywemo or getting other libraries to allow later versions.  @ausil hasn't seen an issue with a newer version installed with `botocore`.  I'm actually surprised that this issue (colloquially known as dependency hell) isn't more common in HA since there are *so* many libraries used if you use a lot of integrations.  Many people don't see this issue, such as myself, since I just don't have one of those other libraries that cause a conflict.  Or, perhaps if I do, it gets installed before pywemo and thus pywemo then upgrades it.

```
$ python3 -m venv .venv
$ . .venv/bin/activate
$ pip install pywemo
Collecting pywemo
  Downloading pywemo-0.6.3-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 3.8 MB/s 
Collecting ifaddr>=0.1.0
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Collecting lxml<5.0,>=4.6
  Using cached lxml-4.6.2-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
Collecting urllib3>=1.26.0
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting requests>=2.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: ifaddr, lxml, urllib3, certifi, chardet, idna, requests, pywemo
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 ifaddr-0.1.7 lxml-4.6.2 pywemo-0.6.3 requests-2.25.1 urllib3-1.26.3
$ pip install botocore==1.19.9
Collecting botocore==1.19.9
  Downloading botocore-1.19.9-py2.py3-none-any.whl (6.7 MB)
     |████████████████████████████████| 6.7 MB 3.2 MB/s 
Collecting urllib3<1.26,>=1.25.4; python_version != "3.4"
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
ERROR: pywemo 0.6.3 has requirement urllib3>=1.26.0, but you'll have urllib3 1.25.11 which is incompatible.
Installing collected packages: urllib3, six, python-dateutil, jmespath, botocore
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.3
    Uninstalling urllib3-1.26.3:
      Successfully uninstalled urllib3-1.26.3
Successfully installed botocore-1.19.9 jmespath-0.10.0 python-dateutil-2.8.1 six-1.15.0 urllib3-1.25.11
$ pip check
pywemo 0.6.3 has requirement urllib3>=1.26.0, but you have urllib3 1.25.11.
```

for fun, lets now install pywemo again:

```
$ pip install pywemo
Requirement already satisfied: pywemo in ./.venv/lib/python3.8/site-packages (0.6.3)
Requirement already satisfied: ifaddr>=0.1.0 in ./.venv/lib/python3.8/site-packages (from pywemo) (0.1.7)
Collecting urllib3>=1.26.0
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Requirement already satisfied: requests>=2.0 in ./.venv/lib/python3.8/site-packages (from pywemo) (2.25.1)
Requirement already satisfied: lxml<5.0,>=4.6 in ./.venv/lib/python3.8/site-packages (from pywemo) (4.6.2)
Requirement already satisfied: idna<3,>=2.5 in ./.venv/lib/python3.8/site-packages (from requests>=2.0->pywemo) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./.venv/lib/python3.8/site-packages (from requests>=2.0->pywemo) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.8/site-packages (from requests>=2.0->pywemo) (2020.12.5)
ERROR: botocore 1.19.9 has requirement urllib3<1.26,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.26.3 which is incompatible.
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.11
    Uninstalling urllib3-1.25.11:
      Successfully uninstalled urllib3-1.25.11
Successfully installed urllib3-1.26.3
$ pip check
botocore 1.19.9 has requirement urllib3<1.26,>=1.25.4; python_version != "3.4", but you have urllib3 1.26.3
```

oops!  It is impossible to get a version that will satisfy both botocore 1.19.9 and pywemo 0.6.3.  This is one of the issues poetry is actually intended to solve --- where it will search all possible dependencies to get "matching" ones that satisfy requirements.  Of course, if you require exactly pywemo==0.6.3 and botocore==1.19.9, then it wouldn't matter anyway since there is no possible way to satisfy the claimed urllib3 requirements of those two versions of those two libraries.

**Comment by esev** [comment]
It's kinda weird though. `botocore` isn't even in https://github.com/home-assistant/core/blob/dev/requirements_all.txt. And `boto3` is expected to be at [1.9.252](https://github.com/home-assistant/core/blob/a066f8482866d69a38f69dd99cc20682565d9f4b/requirements_all.txt#L378). When I did #249 I checked that my home-assistant venv had a newer version of `urllib3` (it had 1.26.2 at the time).

I feel like maybe the upgrade process for HA Core isn't updating the dependencies properly. Where is the upgrade process documented? 

It's also been my assumption that the tests for HA pull in all the (current) dependencies. So I'd expect an issue would be caught in the tests that run as part of sending the PR.

**Comment by esev** [comment]
This is what I usually use for setting up my dev Home Assistant venv. https://developers.home-assistant.io/docs/development_testing/#testing-outside-of-tox

Are there similar instructions for HA Core?

**Comment by Spectre5** [comment]
I'll have to investigate it more later.  Can third party add-ons have additional requirements?  Do they get their own venv or share the main one?  If shared, then perhaps an add on causes the issue?

**Comment by esev** [comment]
Oh! Just realized boto3 isn't in requirements_test_all.txt. So maybe that's where I ran into troubles.

**Comment by Spectre5** [comment]
Good catch, but I'd still think that HA tests the requirements for compatibility before releasing though!  And it doesn't explain the difference in version from master to what ausil has with 1.19.9

**Comment by esev** [comment]
Agreed. FWIW, this is what `pip check` reports for my (mostly stock) Docker container. I would think that a HA Core install would have a similar output. But my knowledge of pip/dependencies isn't great.

```
temperusb 1.5.3 has requirement pyusb>=1.0.0rc1, but you have pyusb 1.0.0b1.
samsungtvws 1.6.0 has requirement websocket-client>=0.57.0, but you have websocket-client 0.54.0.
roonapi 0.0.32 has requirement websocket_client>=0.57.0, but you have websocket-client 0.54.0.
python-jose 3.2.0 has requirement ecdsa<0.15, but you have ecdsa 0.16.1.
pysmarty 0.8 has requirement pymodbus==1.5.2, but you have pymodbus 2.3.0.
pyrebase4 4.4.3 has requirement oauth2client>=4.1.2, but you have oauth2client 4.0.0.
pyicloud 0.10.2 has requirement click<=7.1.1,>=6.0, but you have click 7.1.2.
pyhiveapi 0.3.4.4 has requirement boto3>=1.16.10, but you have boto3 1.9.252.
pyhiveapi 0.3.4.4 has requirement botocore>=1.19.10, but you have botocore 1.13.14.
pyftdi 0.52.9 has requirement pyusb>=1.0.0, but you have pyusb 1.0.0b1.
pycognito 0.1.5 has requirement boto3>=1.10.49, but you have boto3 1.9.252.
pwmled 1.6.7 has requirement adafruit-blinka==5.5.1, but you have adafruit-blinka 6.3.1.
mycroftapi 2.0 has requirement websocket-client==0.44.0, but you have websocket-client 0.54.0.
mitemp-bt 0.0.3 has requirement btlewrap==0.0.8, but you have btlewrap 0.1.0.
miflora 0.7.0 has requirement btlewrap==0.0.10, but you have btlewrap 0.1.0.
meteofrance-api 1.0.1 has requirement pytz<2021.0,>=2020.4, but you have pytz 2021.1.
ibm-watson 4.0.1 has requirement websocket-client==0.48.0, but you have websocket-client 0.54.0.
homematicip 0.13.1 has requirement websocket-client>=0.57.0, but you have websocket-client 0.54.0.
hangups 0.4.11 has requirement protobuf<3.12,>=3.1.0, but you have protobuf 3.15.4.
greeclimate 0.10.3 has requirement pycryptodome==3.9.8, but you have pycryptodome 3.10.1.
eebrightbox 0.0.4 has requirement certifi==2018.11.29, but you have certifi 2020.12.5.
eebrightbox 0.0.4 has requirement idna==2.8, but you have idna 2.10.
eebrightbox 0.0.4 has requirement requests==2.21.0, but you have requests 2.25.1.
eebrightbox 0.0.4 has requirement urllib3==1.24.1, but you have urllib3 1.26.3.
cattrs 1.3.0 has requirement attrs>=20.1.0, but you have attrs 19.3.0.
botocore 1.13.14 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you have python-dateutil 2.8.1.
botocore 1.13.14 has requirement urllib3<1.26,>=1.20; python_version >= "3.4", but you have urllib3 1.26.3.
boto3 1.9.252 has requirement botocore<1.13.0,>=1.12.252, but you have botocore 1.13.14.
```

**Comment by Spectre5** [comment]
So interesting that botocore shows up there!  The order of installs by pip from a requirements file is not guaranteed.  So, I believe that it is possible that doing a `pip install -r requirements.txt` on different machines may result in the libraries being installed in a different order.

See, for example:
https://github.com/pypa/pip/issues/2362#issuecomment-77464857

https://github.com/pypa/pip/issues/3480

I've had an issue like this before where I had a library that needed to be installed before another one.  In that project I ended up using two requirements files to make sure of the install order for that weird case.
