### ISSUE TITLE
arm-linux-gnueabihf-gcc failure

### ISSUE THREAD

**Issue by bnbarnes** [pywemo/pywemo#259]
Encountered the following error when running  .scripts/build.sh on Raspberry pi:
      creating tmp
      cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit0yfg0jlx.c -o tmp/xmlXPathInit0yfg0jlx.o
      /tmp/xmlXPathInit0yfg0jlx.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
       main (int argc, char **argv) {
       ^~~~
      cc tmp/xmlXPathInit0yfg0jlx.o -lxml2 -o a.out
      error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

      ----------------------------------------
  Command "/home/pi/projects/pywemo/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-7ts9a7ll/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-eati5624/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/projects/pywemo/.venv/include/site/python3.7/lxml" failed with error code 1 in /tmp/pip-req-build-7ts9a7ll/

  at .venv/lib/python3.7/site-packages/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):

Debian Buster

**Comment by esev** [comment]
@bnbarnes, see this comment https://github.com/home-assistant/core/issues/46212#issuecomment-780021935. Does that help?

**Comment by Spectre5** [comment]
@bnbarnes, do you have any further update on this?

**Comment by bnbarnes** [comment]
It never built, but I found another source for the app I was using.
Regards, Bruce 

    On Tuesday, May 25, 2021, 03:03:00 PM PDT, Spectre5 ***@***.***> wrote:  
 
 


@bnbarnes, do you have any further update on this?

**Comment by Spectre5** [comment]
alternative solution was found.
