### ISSUE TITLE
Suggestion for Setup section in README

### ISSUE THREAD

**Issue by GarlicToum** [pywemo/pywemo#271]
Big fan of pywemo, thanks for supporting it! I recently changed my network name/password and had to reconfigure my devices, I put them in discovery mode and connected to it directly (using the "Wemo" network).

It might be helpful to mention you can run `arp -a` to get the ip address used to connect.
```
$ arp -a
_gateway (10.22.22.1) at [REMOVED] [ether]
```
and then in python:
```
>>> import pywemo
>>> url = pywemo.setup_url_for_address("10.22.22.1")
>>> device = pywemo.discovery.device_from_description(url)
>>> print(device)
<WeMo Switch "Wemo Mini">
>>> device.setup(ssid='MY SSID', password='MY NETWORK PASSWORD')
('1', 'success')
```

Thanks again! Let me know and I can PR the README if you want!

**Comment by Spectre5** [comment]
Hi @GarlicToum - glad that you're liking pywemo!  Feel free to submit a PR regarding `arp -a` to discover the device on its local network.  I've personally always just used `pywemo.discover_devices()` with good success after connecting to the wemo's local network.

**Comment by GarlicToum** [comment]
Yeah, for some reason the `discover_devices` didn't work for me. Probably something to do with my laptop wifi card or something. PR created!
