### ISSUE TITLE
Support for Wemo motion

### ISSUE THREAD

**Issue by ryanlaux** [pywemo/pywemo#31]
Looking to integrate my wemo motion sensor into my Home Assistant config. The sensor shows up as a switch, but I can't seem to be able to get any on or off state info from it. Does this library support wemo motion? Supposedly ouimeaux supports a get_state line for the sensors

**Comment by pavoni** [comment]
I think we have the ouimeaux Motion code integrated (looks like a place holder really), but I suspect that the motion state isn't returned in the switch state, so probably neither library works at this point.

Probably needs a developer with a Motion and a debugger to take a look at the attributes returned. Will likely be similar to Maker or Insight.

Afraid I don't have a Motion - so need a contribution here (or at least someone to help do the digging).

**Comment by ryanlaux** [comment]
I've opened an issue under this project: https://github.com/thelegendofando/WeMoService/issues

Seems like this guy was able to make a py script to get it working? If I can strip it down to just an http rest command it would probably be useful

**Comment by pavoni** [comment]
The state we want is likely already available from `self.basicevent.GetBinaryState()` or perhaps `self.deviceevent.GetAttributes()`. 

It may even be that the get_state function in `Device` already does the right thing - in which case it already works and just needs to be wired into HA.

If you want to try - load up pywemo as shown here https://github.com/pavoni/pywemo and discover your devices as it describes.

Then type `device[n]` and hit return (where n starts at 0 and add one each time) until you get the Motion device.

They type `device[n].get_state(True)' 

Trigger your Motion - and then just type the command again.

Then wait until the Motion resets and try a third time

If the value changes as we hope - that's what I need to know. Just let me know what it returns and I can wire it into HA.

If that doesn't work we can investigate more.

**Comment by ryanlaux** [comment]
I'll give that a shot when I get back home, thanks

**Comment by ryanlaux** [comment]
Trying to test the discovery.py file, can I just run it? getting an error

`Traceback (most recent call last):
  File "discovery.py", line 6, in <module>
    from . import ssdp
ValueError: Attempted relative import in non-package`

**Comment by ryanlaux** [comment]
Okay got it working with the example provided.. sorry I don't have a lot of coding experience, learning along the way haha. When I ran the script I got a list of my devices:

`pi@raspberrypi:~ $ python Wemo.py device[0]
/home/pi/pywemo/ssdp.py:142: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if tree:
[<WeMo Switch "Chris Lights">, <WeMo Switch "TV Lights">, <WeMo Switch "Party">, <WeMo Motion "Door Sensor">, <WeMo Switch "Ryan Lights">]`

Where do I enter the device[0]?

**Comment by ryanlaux** [comment]
Okay I figured it out! It works and it returned a 1 when I triggered then reverted to 0 when it reset!

**Comment by ryanlaux** [comment]
Also tested with a python script to print when triggered, and I'm getting it to change when streaming device status. Look like it should work

**Comment by pavoni** [comment]
Cool - thanks. Will take a look at the HA code. Closing this issues - since it's already supported here.
