### ISSUE TITLE
Thoughts about a version 1.0.0 release?

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#317]
After #293 I think pyWeMo now has support for all WeMo UPnP-based devices. What do folks think about making the next release a version 1.0.0 release?

Over time, we've been adding a number of deprecation warnings to the code. With semantic versioning it is typically okay to make non-backward compatible changes when changing the major release number. This would give us an opportunity to remove the deprecation warnings as well.

Are there other places in the code where we've wanted to change an argument or method name but have been holding back due to keeping the code backward compatible?

**Comment by esev** [comment]
Looking at pywemo/ssdp.py, I think we could probably deprecate & remove pywemo.ssdp.SSDP & a few properties from pywemo.ssdp.UPNPEntry (expired, is_expired, description, match_device_description). None of those are used within pyWeMo.

**Comment by Spectre5** [comment]
Makes sense, maybe do this after type hints are finished being incorporated (which is probably your plan already)?

That said, although not technically correct per semantic versioning, I do see libraries add deprecation with minor releases.  Typically the deprecation message will then indicate what minor release will drop the feature/functionality.  For example, I know matplotlib does has done this.

**Comment by esev** [comment]
There have been quite a few breaking changes since the last release, including some that'll break Home Assistant. I definitely plan to list all the breaking changes in the release notes, but figured it would be worth surveying other projects that use pyWeMo and fix the ones that use recent versions of pyWeMo before the next release.

I'll keep editing this as more are surfaced:

### Home Assistant (uses pinned release):

1. #432 [[code](https://github.com/home-assistant/core/blob/117ab4a0e5b319fee7133ad8b8278e1355f3938a/homeassistant/components/wemo/light.py#L74)]
2. #369 [[code](https://github.com/home-assistant/core/blob/26b78d2a7a08a0da8de772d86828de4424da9b9b/homeassistant/components/wemo/entity.py#L56)]

### TerrariumPI (uses dependabot)

1. #367 [[code](https://github.com/theyosh/TerrariumPI/blob/79be755b0a0dd3260a6db00b1b5e0535a8dbd1c5/hardware/relay/wemo_relay.py#L23)] [[fix in #808](https://github.com/theyosh/TerrariumPI/pull/808)]
