### ISSUE TITLE
Add integration test for the CrockPot device

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#335]
Integration tests make it easier to maintain pyWeMo, helping to ensure updates to the code function as expected. It'd be great if we could have an integration test for the CrockPot device.

There is a test file below. If someone has a WeMo CrockPot device, these are the steps needed to add the test.

1. Clone the pywemo git repository locally.
2. Add a new test file named `tests/ouimeaux_device/test_crockpot.py`. This should be in the same directory as all the other `test_<device>.py` files. Populate this file with the test code below.
3. Change the IP address and port in the test file to match that of your CrockPot device. If needed, see the top level pywemo readme for how to discover the device.
4. Edit `scripts/build.sh` to remove just the `--vcr-record=none` argument on [line 57](https://github.com/pywemo/pywemo/blob/5613bf558f1eda1473991fa72ddf25bc83286872/scripts/build.sh#L57).
5. Run `./scripts/build.sh` or the equivalent commands to create a venv, fetch the dev dependencies, and run the tests.
6. This should produce a `tests/vcr/tests.ouimeaux_device.test_crockpot` directory containing the http requests that took place with the device. Upload this as a .zip attached to this issue, or submit a pull request with the test code and files.

The test below may not look like much, but having the actual device responses from # 6 is the real benefit to these [vcr](https://github.com/kevin1024/vcrpy#rationale) integration tests. Many thanks in advance to anyone willing to contribute here!!

```python
"""Integration tests for the WeMo CrockPot."""

import pytest

from pywemo.ouimeaux_device.crockpot import CrockPot, CrockPotMode


@pytest.fixture
def crockpot(vcr):
    with vcr.use_cassette("crockpot_setup.yaml"):
        return CrockPot("http://192.168.1.100:49153/setup.xml")


@pytest.mark.vcr()
def test_on(crockpot):
    crockpot.on()

    assert crockpot.mode == CrockPotMode.High


@pytest.mark.vcr()
def test_off(crockpot):
    crockpot.off()

    assert crockpot.mode == CrockPotMode.Off
```

**Comment by esev** [comment]
@alexanv1 is this something you could help with?

**Comment by roblandry** [comment]
I know this has been a while, but i have the requested data. 

[tests.ouimeaux_device.test_crockpot.zip](https://github.com/pywemo/pywemo/files/9332148/tests.ouimeaux_device.test_crockpot.zip)
