### ISSUE TITLE
Implement UNSUBSCRIBE for compatibility

### ISSUE THREAD

**Issue by jfroy** [pywemo/pywemo#350]
This is probably low priority, but I wonder if the WeMo firmware will slightly misbehave by receiving 501 for UNSUBSCRIBE commands.

`2689	1171.134476	192.168.1.121	192.168.1.178	HTTP	236	UNSUBSCRIBE /upnp/event/basicevent1 HTTP/1.1`

```
Hypertext Transfer Protocol
    UNSUBSCRIBE /upnp/event/basicevent1 HTTP/1.1\r\n
    HOST: 192.168.1.178:8989\r\n
    SID: uuid:a74b23d5-34b9-4f71-9f87-bed24353f304\r\n
    USER-AGENT: Unspecified, UPnP/1.0, Unspecified\r\n
    \r\n
    [Full request URI: http://192.168.1.178:8989/upnp/event/basicevent1]
```

`2692	1171.137700	192.168.1.178	192.168.1.121	HTTP	570	HTTP/1.0 501 Unsupported method ('UNSUBSCRIBE')  (text/html)`

I'm perfectly happy with closing this as "won't do". I didn't see an existing issue about it.

**Comment by Spectre5** [comment]
I agree that we should implement it.
