### ISSUE TITLE
Poetry version mismatch causes pre-commit to fail.

### ISSUE THREAD

**Issue by esev** [pywemo/pywemo#413]
The pre-commit checks can fail when the Poetry version on the host is different from the Poetry version used by pyWeMo. More details on #411.

I believe this is happening due to the `poetry-lock-check` added in #382.

**Comment by Spectre5** [comment]
Yup, spot on

**Comment by esev** [comment]
Some quick testing outside the venv

```bash
$ pip install poetry==1.5.0
...
$ poetry --version
Poetry (version 1.5.0)
$ poetry run poetry --version
Poetry (version 1.4.2)
```

**Comment by Spectre5** [comment]
Haha...ya, I was going to suggest `poetry run poetry` as a possible work around.  Seems a bit awkward, does that still work if you do have the virtual environment active?

**Comment by esev** [comment]
It does :)

```bash
$ . .venv/bin/activate
(.venv) $ poetry run poetry --version
Poetry (version 1.4.2)
```

We must go deeper! /s

**Comment by Spectre5** [comment]
Funny, ha.

You might get some inspiration from nox-poetry.  Check out it's noxfile, specifically the `activate_virtualenv_in_precommit_hooks` function.  It basically modifies the pre-commit hook when it installs to activate the virtual environment and use it.  Then you don't actually need to call poetry directly in the pre-commit file itself since all runs will have the environment activated...

**Comment by Spectre5** [comment]
So, you could do a similar edit when installing pre-commit in the build.sh file.

**Comment by esev** [comment]
I'll look more at `nox-poetry` tonight.

Does nox-poetry need to be installed outside the venv though? Ideally I'd like to find a solution where all the dependencies are the same across all dev environments. I was thinking the easiest way to do that was to always cause things to execute inside the venv. `activate_virtualenv_in_precommit_hooks` looks like it does that, but I need to look at how to bootstrap nox-poetry.

I was also thinking about using [poetry-pre-commit-plugin](https://github.com/vstrimaitis/poetry-pre-commit-plugin) as a way to install the pre-commit hooks. I wonder if the owner of that project would be open to a PR that provides an option for making the same modification to the pre-commit hook.

**Comment by Spectre5** [comment]
For nox-poetry, I just meant to use that function for inspiration to perform that same action ourself, not to use nox-poetry itself (unless perhaps we eventually use nox itself).

Asking that poetry plugin to add this as an option seems reasonable though.  You can see that plugin is fairly small too..so another option would be to just make a new plugin for this single purpose.  Could put it in pywemo for the moment, though eventually it'd probably be better as a standalone project.

**Comment by esev** [comment]
Ah! Thanks for clarifying. I think a new plugin, that runs after the poetry-pre-commit-plugin, will do the trick nicely for now. It can implement something similar to `activate_virtualenv_in_precommit_hooks`.

Note to self: [add_listener](https://github.com/python-poetry/cleo/blob/db7826071ac556fb181a3fd5025f535ed37d90ab/src/cleo/events/event_dispatcher.py#L68) has a `priority` arg. poetry-pre-commit-plugin [uses the default priority](https://github.com/vstrimaitis/poetry-pre-commit-plugin/blob/23d47afb4201c2a756272debd25b6d2b0959f24a/src/poetry_pre_commit_plugin/plugin.py#L19).

**Comment by Spectre5** [comment]
And it sorts by negative priority, so probably need to use priority of -1 in any new plugin.  It may be worth asking that pre-commit plugin to hard code a priority of 1 or 5 or something, or perhaps even better to add an option to pass it a priority to use.
