### ISSUE TITLE
Discovery results in UnicodeDecodeError

### ISSUE THREAD

**Issue by retrostrobe** [pywemo/pywemo#46]
Hi there,
I'm on a RPi3 and using the latest dev version of PyWeMo. This may be a known error, but I couldn't find a reference to it and would like to highlight the following issue when I try to discover devices using the Python command-line. Adding devices manually works.

> import pywemo
> devices = pywemo.discover_devices()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/pywemo-0.4.2-py3.4.egg/pywemo/discovery.py", line 19, in discover_devices
>     ssdp_entries = ssdp.scan(st, max_entries=max_devices, match_mac=match_mac)
>   File "/usr/local/lib/python3.4/dist-packages/pywemo-0.4.2-py3.4.egg/pywemo/ssdp.py", line 239, in scan
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)

The only change I've done, as per #23, is to edit the default IP address in ssdp.py to replace it with the localhost one, which works with HomeAssistant. 

Any insight into the discovery issue would be grateful. Thanks.

**Comment by jaharkes** [comment]
Looks like we should probably try to decode the response as UTF-8 instead of ascii.

**Comment by retrostrobe** [comment]
Unfortunately, I'm getting the same error. Now, the weird thing is that I have managed to make it work once or twice. I haven't changed anything, sometimes it works, but most often it doesn't. Don't sweat over this bug though, I've decided to use static IPs instead since it works. 

> devices = pywemo.discover_devices()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/pywemo-0.4.3-py3.4.egg/pywemo/discovery.py", line 19, in discover_devices
>     ssdp_entries = ssdp.scan(st, max_entries=max_devices, match_mac=match_mac)
>   File "/usr/local/lib/python3.4/dist-packages/pywemo-0.4.3-py3.4.egg/pywemo/ssdp.py", line 239, in scan
>     response = sock.recv(1024).decode("UTF-8")
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1: invalid continuation byte
