### ISSUE TITLE
Cannot install on synology NAS

### ISSUE THREAD

**Issue by brownad** [pywemo/pywemo#48]
Hi,

I have tried to install this dependency on Synology via home assistant installation but fails as it needs to compile is there a way to deploy this?

**Comment by pavoni** [comment]
Can you install / use pywemo standalone on Synology (as described in the read.me)? May help track down the issue.

**Comment by brownad** [comment]
Think it's with netifaces here's the output

ash-4.3# python3 -m pip install pywemo==0.4.3
Collecting pywemo==0.4.3
  Downloading pywemo-0.4.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages (from pywemo==0.4.3)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages (from pywemo==0.4.3)
Collecting netifaces>=0.10.0 (from pywemo==0.4.3)
  Using cached netifaces-0.10.4.tar.gz
Building wheels for collected packages: netifaces
  Running setup.py bdist_wheel for netifaces ... error
  Complete output from command /bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-2na5zkqc/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmpz3td5b36pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  checking for getifaddrs...not found.
  checking for getnameinfo...not found.
  checking for socket IOCTLs...not found.
  checking for optional header files...none found.
  checking whether struct sockaddr has a length field...no.
  checking which sockaddr_xxx structs are defined...none!
  checking for routing socket support...no.
  checking for sysctl(CTL_NET...) support...no.
  checking for netlink support...no.
  building 'netifaces' extension
  /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DOPENSSL_NO_SSL3 -DOPENSSL_NO_SSL2 -DSYNOPLAT_F_ARMV5 -DSYNO_MARVELL_88F6281 -O2 -DBUILD_ARCH=32 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DSYNO_PLATFORM=MARVELL_88F6281 -g -DSDK_VER_MIN_REQUIRED=600 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -O2 -Wno-unused-result -fPIC -DNETIFACES_VERSION=0.10.4 -I/volume1/@appstore/py3k/usr/local/include/python3.5m -c netifaces.c -o build/temp.linux-armv5tel-3.5/netifaces.o
  unable to execute '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc': No such file or directory
  error: command '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc' failed with exit status 1

---

  Failed building wheel for netifaces
  Running setup.py clean for netifaces
Failed to build netifaces
Installing collected packages: netifaces, pywemo
  Running setup.py install for netifaces ... error
    Complete output from command /bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-2na5zkqc/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-lj_9zqf6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    checking for getifaddrs...not found.
    checking for getnameinfo...not found.
    checking for socket IOCTLs...not found.
    checking for optional header files...none found.    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...none!
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...no.
    building 'netifaces' extension
    /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DOPENSSL_NO_SSL3 -DOPENSSL_NO_SSL2 -DSYNOPLAT_F_ARMV5 -DSYNO_MARVELL_88F6281 -O2 -DBUILD_ARCH=32 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DSYNO_PLATFORM=MARVELL_88F6281 -g -DSDK_VER_MIN_REQUIRED=600 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -O2 -Wno-unused-result -fPIC -DNETIFACES_VERSION=0.10.4 -I/volume1/@appstore/py3k/usr/local/include/python3.5m -c netifaces.c -o build/temp.linux-armv5tel-3.5/netifaces.o
    unable to execute '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc': No such file or directory
    error: command '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc' failed with exit status 1

```
----------------------------------------
```

Command "/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-2na5zkqc/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-lj_9zqf6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2na5zkqc/netifaces/
ash-4.3#

**Comment by pavoni** [comment]
Looks like there may be some advice here https://forum.synology.com/enu/viewtopic.php?t=81
