### ISSUE TITLE
https://github.com/pywemo/pywemo/blob/a3bae77da110eeb1c7985393e9ec3ef5f8b89fdf/poetry.lock

### ISSUE THREAD

**Issue by Stefan41199** [pywemo/pywemo#483]
https://github.com/pywemo/pywemo/blob/a3bae77da110eeb1c7985393e9ec3ef5f8b89fdf/poetry.lock

**Comment by esev** [comment]
Please add some additional details describing the issue.

I'll close this for now, but please re-open if there is an issue.
