### ISSUE TITLE
pywemo.subscribe: Received event for unregistered device

### ISSUE THREAD

**Issue by nar00n** [pywemo/pywemo#56]
pywemo.subscribe: Received event for unregistered device

The issue happens when i use hostname instead of the ip address , once the hostname is changed to ip address it works.

**Comment by pavoni** [comment]
Yes - if you use discovery this will take care of itself.

If you use the probe approach then you need to use ip addresses as show in the examples.

This is because we check look up where the subscriptions came from based on the senders IP address. I'll make this clearer in the documentation.
