### ISSUE TITLE
Unable to probe socket 

### ISSUE THREAD

**Issue by kylejohnson** [pywemo/pywemo#57]
I have a WeMo socket device that is being probed, but that, due to 
https://github.com/pavoni/pywemo/blob/a43cbd1715476ad8854858c2e04966eb040c123e/pywemo/ouimeaux_device/__init__.py#L31, is not able to be used.  Specifically, there is no `<firmwareVersion>` tag reported by the socket device, where-as it is reported by light switches.

If I remove L31 and then un-indent L32, the probe works just fine, and I can successfully discover and use the device.

```xml
<device>
   <deviceType>urn:Belkin:device:controllee:1</deviceType>
   <friendlyName>Humidifier Switch</friendlyName>
   <manufacturer>Belkin International Inc.</manufacturer>
   <manufacturerURL>http://www.belkin.com</manufacturerURL>
   <modelDescription>Belkin Plugin Socket 1.0</modelDescription>
   <modelName>Socket</modelName>
   <modelNumber>1.0</modelNumber>
   <modelURL>http://www.belkin.com/plugin/</modelURL>
   <serialNumber>SN</serialNumber>
   <UDN>uuid:Socket-1_0-SN</UDN>
   <UPC>123456789</UPC>
</device>
```

**Comment by kk7ds** [comment]
If we remove that line then we will discover any http interface on that port as a wemo. Maybe we could check for something else (possibly in addition to WeMo)? Maybe parse the xml and check for a few keys?

**Comment by jaharkes** [comment]
Maybe check if manufacturer starts with Belkin? As far as I've seen that seems to be even for non Belkin devices. I believe the humidifier is sold in the US as Holmes and I'm guessing this must be that humidifier.

As an aside, I wonder if the humidifier exposes a humidity sensor value in the responses somehow.

**Comment by kylejohnson** [comment]
It is indeed odd that they wouldn't have a `firmwareVersion` tag exported on the socket, but that they do export it on the switch.  I agree that /something/ should be checked for.  Perhaps the `modelDescription` would be best?  It describes the manufacturer, as well as the model.

.100 and .102 are both light switches, and .103 is the socket.
```
-bash-4.3$ curl -s http://192.168.14.100:49153/setup.xml|grep -E "(modelDescription|firmwareVersion)"
    <modelDescription>Belkin Plugin Socket 1.0</modelDescription>
<firmwareVersion>WeMo_WW_2.00.10885.PVT-OWRT-LS</firmwareVersion>

-bash-4.3$ curl -s http://192.168.14.102:49153/setup.xml|grep -E "(modelDescription|firmwareVersion)"
    <modelDescription>Belkin Plugin Socket 1.0</modelDescription>
<firmwareVersion>WeMo_WW_2.00.10885.PVT-OWRT-LS</firmwareVersion>

-bash-4.3$ curl -s http://192.168.14.103:49153/setup.xml|grep -E "(modelDescription|firmwareVersion)"
    <modelDescription>Belkin Plugin Socket 1.0</modelDescription>
```

**Comment by pavoni** [comment]
Good thoughts. I think @kk7ds's suggestion of parsing the XML is the best option.

But as a quick fix I imagine checking for `Wemo` or `Belkin` in the text would do the trick (and prevent something we don't understand causing trouble).

**Comment by pavoni** [comment]
Or you could look to `Belkin` and `Humidifier` as well as `weMo`. PR welcome!

**Comment by kylejohnson** [comment]
I'm going to submit a PR to look for `Belkin`.  Do any of you have other Belkin devices to test with?  I have only the two types of switches / sockets.

**Comment by pavoni** [comment]
I have some insight sockets, switch sockets and some makers. I don't have lights or motion sensors.

Probably best to keep the 'WeMo' test - and add another. That way all the existing devices will work as they do now - and any bugs will involve finding new devices that we didn't expect.
