### ISSUE TITLE
Change subscriptions to update cached params 

### ISSUE THREAD

**Issue by pavoni** [pywemo/pywemo#67]
When using subscriptions it would be good to use the data in the subscription callbacks - rather than force the client to refetch the data.

Particularly useful now insight params are updated every second for an active device.

@jumpkick's recent PR points the direction in adding the insight subscription.

I suspect this means we'll want to subscribe to multiple events types for devices that support then (eg insight switches have `basic` and `insight` events) - but only once we stop calling back to the device for every update.

0.4.13 traces what the callback type is - and params that were passed - so should make reverse engineering easier!.

@stu-gott's code for the coffeemaker has the basics which we could adapt / extend for other devices.

@jaharkes Suspect the bridge will be the most complex!

**Comment by pavoni** [comment]
I suspect we should now close this @esev do you have a view

**Comment by esev** [comment]
I think it can be closed too. I think the bridge might be the only device that doesn't do this at the moment. But the bridge is also not setup for a subscription in home assistant either.
