### ISSUE TITLE
_x might be average watts

### ISSUE THREAD

**Issue by deftdawg** [pywemo/pywemo#68]
The value `_x` @ https://github.com/pavoni/pywemo/blob/master/pywemo/ouimeaux_device/insight.py#L21 is documented as being Average Power in Watts here: https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBinding.java#L200

For me the app lists my average power as being 72w, and this value is only 61, so I'm not sure what time scale it is averaged over.

**Comment by deftdawg** [comment]
Watching TV today, _x is 147w, app reports 131-158W instant power...  

Definitely does appear to be pretty close to Average Wattage to me

Prior to starting, I did a firmware update about 10 hours earlier, the value was 0 after that until I turned on the TV (outlet was in standby because of Apple TV drawing ~4w (less than the 8w standby threshold power)).

**Comment by pavoni** [comment]
I have 2 insights. One has a `Avg when on`  in the app of 42w - and the `_x` parameter is 42.
Sadly the other has an `Avg when on` in the app of 995W - and the `_x` parameter is 381.

So we need to do some more digging...

**Comment by pavoni** [comment]
In case anyone else wants to play - the data from my devices 
```
'state': '8', 
'lastchange': datetime.datetime(2017, 3, 26, 12, 45, 44), 
'totalmwm': 25323740, 
'powerthreshold': 8000, 
'ontoday': 7032, 
'ontotal': 35715, 
'currentpower': 0, 
'timeperiod': '1209600', 
'todaymwm': 5002193, 
'_x': '43', 
'onfor': 7032
```
and
```
'state': '0', 
'lastchange': datetime.datetime(2017, 3, 25, 22, 24, 22), 
'totalmwm': 146574354,
'powerthreshold': 8000, 
'ontoday': 0, 
'ontotal': 8832, 
'currentpower': 0, 
'timeperiod': '1209600', 
'todaymwm': 0, 
'_x': '381', 
'onfor': 42
```

**Comment by jaharkes** [comment]
I seem to get the right values when I divide 'total milliwatt / minute' by 'ontotal seconds'. i.e.

    (25323740 / 1000.) / (35715 / 60.) = 42.543...
    (146574354 / 1000.) / (8832 / 60.) = 995.749...

**Comment by pavoni** [comment]
Which is great (and perhaps a calculation we should do) - but doesn't explain what `_x` means.

**Comment by pavoni** [comment]
Closing this for now since `_x` probably isn't average watts.
