### ISSUE TITLE
devices with multiple switches on different ports not handled

### ISSUE THREAD

**Issue by ausil** [pywemo/pywemo#76]
the probe_wemo function seems to have an assumption that a ip can only ever have a single devices and listening port. 

I have some devices that has 8 switched ports it is emulating a wemo device. it is listening on ports 49153-49159. homeassistant is using pywemo in part of the discovery. currently it only finds a single switch for each device. I think I almost have a patch ready to be submitted. but wanted to see if you had ideas on how it should be done

**Comment by pavoni** [comment]
I'm going to close this for now - since this isn't an official wemo device.

Open to a new PR...
