### ISSUE TITLE
Python3 not supported

### ISSUE THREAD

**Issue by allyunion** [pywemo/pywemo#96]
[In [1]: import pywemo
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-46a436f57ad8> in <module>()
----> 1 import pywemo

/usr/local/lib/python3.5/dist-packages/pywemo/__init__.py in <module>()
      3 """
      4 
----> 5 from .ouimeaux_device import Device as WeMoDevice
      6 from .ouimeaux_device.insight import Insight
      7 from .ouimeaux_device.lightswitch import LightSwitch

/usr/local/lib/python3.5/dist-packages/pywemo/ouimeaux_device/__init__.py in <module>()
      8 
      9 import requests
---> 10 from requests import ConnectTimeout
     11 from requests import ConnectionError
     12 from requests import Timeout

-----

This has to do with the fact that the exceptions for requests in Python3 has moved to a subclass/module -- basically it's from requests.exceptions in Python3

**Comment by pavoni** [comment]
This has been a Python 3 library for quite some time.

Suspect something is wrong in your environment - see my Python 3.6.3 import below,
```
❯ python
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywemo
>>>
```
